# Generated by Django 5.2.6 on 2026-08-19 07:08

import apps.common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(default='Electronics Store', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage applied at checkout. Snapshotted onto each order.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_inclusive_pricing', models.BooleanField(default=False, help_text='True when catalogue prices already include VAT.')),
                ('cod_enabled', models.BooleanField(default=True)),
                ('cod_max_order_value', apps.common.fields.MoneyField(blank=True, help_text='Orders above this cannot use Cash on Delivery. Null disables the cap.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_digest_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses for the cron-invoked low-stock digest.')),
            ],
            options={
                'verbose_name_plural': 'store settings',
                'db_table': 'dashboard_store_settings',
            },
        ),
    ]
