# Generated by Django 5.2.6 on 2026-08-19 10:13

from django.db import migrations, models

OLD_NAME = "Electronics Store"
NEW_NAME = "MicroMart"


def _rename(apps, schema_editor, old, new):
    """Move the singleton row only while it still holds the placeholder.

    StoreSettings is a pk=1 singleton, so a default change alone leaves any
    already-seeded database on the old name. Guarding on the previous value
    means an owner who has already renamed the store through the admin keeps
    their name.
    """
    StoreSettings = apps.get_model("dashboard", "StoreSettings")
    StoreSettings.objects.filter(pk=1, store_name=old).update(store_name=new)


def rename_forward(apps, schema_editor):
    _rename(apps, schema_editor, OLD_NAME, NEW_NAME)


def rename_backward(apps, schema_editor):
    _rename(apps, schema_editor, NEW_NAME, OLD_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='MicroMart', max_length=120),
        ),
        migrations.RunPython(rename_forward, rename_backward),
    ]
