# Generated by Django 5.2.6 on 2026-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_storesettings_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='MicroMart', max_length=120),
        ),
    ]
