"""
Demo catalogue product data.

**What this is and is not.** The model designations, socket names, capacities
and speeds below are factual hardware attributes -- the sort of thing a
spec sheet or a price list carries, and not anyone's creative expression.
Marketing copy is *not* reproduced: `description` is absent from every record
here and is composed at seed time from the record's own specs and highlights
(`build_description()` in the seed command), so the prose on the site is this
project's own. Images are likewise generated locally as lettered placeholder
tiles; nothing is downloaded from any retailer.

Prices are indicative BDT figures for a Bangladeshi storefront. They are demo
data, not a quote.

Field notes:
  * `price` / `was` are integers in BDT. `was` is the compare-at; omit it for
    a product that is not discounted, because a catalogue where everything is
    on sale makes the badge meaningless.
  * `component` attaches a PC-builder profile. Only parts that can go in a
    build carry one, and its fields are what the compatibility rules read.
  * `variants` is optional. Omitted, the seeder creates one default variant --
    the invariant that every product has at least one variant holds either
    way.
"""


def P(name, brand, category, price, *, model="", was=None, stock=12, warranty=12,
      highlights=(), specs=None, component=None, variants=None, featured=False):
    """Terse constructor -- the alternative is 130 dicts of mostly key names."""
    return {
        "name": name,
        "brand": brand,
        "category": category,
        "model": model,
        "price": price,
        "was": was,
        "stock": stock,
        "warranty": warranty,
        "highlights": list(highlights),
        "specs": specs or {},
        "component": component,
        "variants": variants,
        "featured": featured,
    }


PRODUCTS = [
    # ----------------------------------------------------------------- CPU
    P(
        "AMD Ryzen 5 5600X Desktop Processor", "AMD", "processor", 16500,
        model="100-100000065BOX", was=18900, stock=26, warranty=36, featured=True,
        highlights=[
            "6 cores and 12 threads for gaming and everyday multitasking",
            "Boosts to 4.6GHz without manual tuning",
            "Drops into any AM4 board with a current BIOS",
        ],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Ryzen 5"),
                        ("Socket", "AM4"), ("Packaging", "Retail box")],
            "Performance": [("Cores", "6"), ("Threads", "12"),
                            ("Base Clock", "3.7GHz"), ("Boost Clock", "4.6GHz"),
                            ("L3 Cache", "32MB"), ("Lithography", "7nm")],
            "Power": [("TDP", "65W"), ("Cooler Included", "No")],
            "Memory": [("Supported Memory", "DDR4-3200"), ("Memory Channels", "2")],
        },
        component={"slot": "cpu", "socket": "AM4", "tdp_watts": 65},
    ),
    P(
        "AMD Ryzen 7 5800X Desktop Processor", "AMD", "processor", 24500,
        model="100-100000063WOF", was=27900, stock=14, warranty=36,
        highlights=["8 cores and 16 threads", "4.7GHz boost clock", "AM4 socket"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Ryzen 7"),
                        ("Socket", "AM4")],
            "Performance": [("Cores", "8"), ("Threads", "16"),
                            ("Base Clock", "3.8GHz"), ("Boost Clock", "4.7GHz"),
                            ("L3 Cache", "32MB")],
            "Power": [("TDP", "105W"), ("Cooler Included", "No")],
            "Memory": [("Supported Memory", "DDR4-3200"), ("Memory Channels", "2")],
        },
        component={"slot": "cpu", "socket": "AM4", "tdp_watts": 105},
    ),
    P(
        "AMD Ryzen 5 7600 Desktop Processor", "AMD", "processor", 23500,
        model="100-100001015BOX", stock=18, warranty=36,
        highlights=["6 Zen 4 cores on the AM5 platform", "DDR5 memory support",
                    "Ships with a Wraith Stealth cooler"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Ryzen 5"),
                        ("Socket", "AM5")],
            "Performance": [("Cores", "6"), ("Threads", "12"),
                            ("Base Clock", "3.8GHz"), ("Boost Clock", "5.1GHz"),
                            ("L3 Cache", "32MB"), ("Lithography", "5nm")],
            "Power": [("TDP", "65W"), ("Cooler Included", "Yes")],
            "Memory": [("Supported Memory", "DDR5-5200"), ("Memory Channels", "2")],
        },
        component={"slot": "cpu", "socket": "AM5", "tdp_watts": 65},
    ),
    P(
        "AMD Ryzen 7 7800X3D Desktop Processor", "AMD", "processor", 46500,
        model="100-100000910WOF", was=51000, stock=7, warranty=36, featured=True,
        highlights=["96MB of 3D V-Cache aimed squarely at gaming",
                    "8 Zen 4 cores", "AM5 socket, DDR5 memory"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Ryzen 7"),
                        ("Socket", "AM5")],
            "Performance": [("Cores", "8"), ("Threads", "16"),
                            ("Base Clock", "4.2GHz"), ("Boost Clock", "5.0GHz"),
                            ("L3 Cache", "96MB")],
            "Power": [("TDP", "120W"), ("Cooler Included", "No")],
            "Memory": [("Supported Memory", "DDR5-5200"), ("Memory Channels", "2")],
        },
        component={"slot": "cpu", "socket": "AM5", "tdp_watts": 120},
    ),
    P(
        "Intel Core i5-12400F Desktop Processor", "Intel", "processor", 15900,
        model="BX8071512400F", was=17500, stock=22, warranty=36,
        highlights=["6 performance cores", "Excellent value for a 1080p build",
                    "Requires a discrete graphics card"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Core i5"),
                        ("Socket", "LGA1700"), ("Generation", "12th Gen")],
            "Performance": [("Cores", "6"), ("Threads", "12"),
                            ("Base Clock", "2.5GHz"), ("Turbo Clock", "4.4GHz"),
                            ("Cache", "18MB")],
            "Power": [("TDP", "65W"), ("Cooler Included", "Yes")],
            "Graphics": [("Integrated Graphics", "None")],
        },
        component={"slot": "cpu", "socket": "LGA1700", "tdp_watts": 65},
    ),
    P(
        "Intel Core i5-13400 Desktop Processor", "Intel", "processor", 22500,
        model="BX8071513400", stock=16, warranty=36,
        highlights=["10 cores in a hybrid performance/efficiency layout",
                    "Integrated UHD 730 graphics", "LGA1700 socket"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Core i5"),
                        ("Socket", "LGA1700"), ("Generation", "13th Gen")],
            "Performance": [("Cores", "10 (6P + 4E)"), ("Threads", "16"),
                            ("Turbo Clock", "4.6GHz"), ("Cache", "20MB")],
            "Power": [("TDP", "65W"), ("Cooler Included", "Yes")],
            "Graphics": [("Integrated Graphics", "Intel UHD 730")],
        },
        component={"slot": "cpu", "socket": "LGA1700", "tdp_watts": 65},
    ),
    P(
        "Intel Core i7-13700K Desktop Processor", "Intel", "processor", 44900,
        model="BX8071513700K", was=48500, stock=9, warranty=36,
        highlights=["16 cores for heavy multitasking", "Unlocked for overclocking",
                    "Needs a capable cooler"],
        specs={
            "General": [("Type", "Desktop Processor"), ("Series", "Core i7"),
                        ("Socket", "LGA1700"), ("Generation", "13th Gen")],
            "Performance": [("Cores", "16 (8P + 8E)"), ("Threads", "24"),
                            ("Turbo Clock", "5.4GHz"), ("Cache", "30MB")],
            "Power": [("TDP", "125W"), ("Cooler Included", "No")],
            "Graphics": [("Integrated Graphics", "Intel UHD 770")],
        },
        component={"slot": "cpu", "socket": "LGA1700", "tdp_watts": 125},
    ),

    # -------------------------------------------------------------- Cooler
    P(
        "Cooler Master Hyper 212 Black Edition CPU Cooler", "Cooler Master",
        "cpu-cooler", 4200, model="RR-212S-20PK-R1", stock=30, warranty=24,
        highlights=["Four direct-contact heat pipes", "120mm PWM fan",
                    "Fits both AMD and Intel mounts"],
        specs={
            "General": [("Type", "Air Cooler"), ("Colour", "Black")],
            "Cooling": [("Heat Pipes", "4"), ("Fan Size", "120mm"),
                        ("Fan Speed", "650-2000 RPM"), ("Noise Level", "26 dBA")],
            "Compatibility": [("Intel Sockets", "LGA1700 / LGA1200 / LGA115x"),
                              ("AMD Sockets", "AM5 / AM4")],
            "Dimensions": [("Height", "159mm")],
        },
        component={"slot": "cooler", "supported_sockets": ["AM4", "AM5", "LGA1700", "LGA1200"],
                   "cooler_max_tdp_watts": 150, "height_mm": 159, "power_watts": 5},
    ),
    P(
        "Thermaltake UX200 SE ARGB CPU Air Cooler", "Thermaltake", "cpu-cooler", 2450,
        model="CL-P099-AL12SW-A", stock=34, warranty=24,
        highlights=["Budget ARGB tower cooler", "Quiet 120mm fan",
                    "Straightforward push-pin mounting"],
        specs={
            "General": [("Type", "Air Cooler"), ("Lighting", "ARGB")],
            "Cooling": [("Fan Size", "120mm"), ("Fan Speed", "500-1800 RPM"),
                        ("Noise Level", "25.4 dBA")],
            "Compatibility": [("Intel Sockets", "LGA1700 / LGA1200 / LGA115x"),
                              ("AMD Sockets", "AM4")],
            "Dimensions": [("Height", "155mm")],
        },
        component={"slot": "cooler", "supported_sockets": ["AM4", "LGA1700", "LGA1200"],
                   "cooler_max_tdp_watts": 95, "height_mm": 155, "power_watts": 4},
    ),
    P(
        "Corsair iCUE H100i Elite 240mm Liquid CPU Cooler", "Corsair", "cpu-cooler",
        16500, model="CW-9060058-WW", was=18500, stock=8, warranty=60,
        highlights=["240mm radiator for high-wattage processors",
                    "Two 120mm ML RGB fans", "Software fan and lighting control"],
        specs={
            "General": [("Type", "Liquid Cooler (AIO)"), ("Radiator Size", "240mm")],
            "Cooling": [("Fan Size", "2 x 120mm"), ("Fan Speed", "400-2400 RPM"),
                        ("Noise Level", "36 dBA")],
            "Compatibility": [("Intel Sockets", "LGA1700 / LGA1200"),
                              ("AMD Sockets", "AM5 / AM4")],
            "Dimensions": [("Radiator Thickness", "27mm")],
        },
        component={"slot": "cooler", "supported_sockets": ["AM4", "AM5", "LGA1700", "LGA1200"],
                   "cooler_max_tdp_watts": 250, "height_mm": 60, "power_watts": 12},
    ),

    # ---------------------------------------------------------- Motherboard
    P(
        "MSI PRO B550M-A WiFi Micro-ATX Motherboard", "MSI", "motherboard", 13500,
        model="PRO B550M-A WIFI", was=15200, stock=15, warranty=36,
        highlights=["AM4 socket with DDR4 support", "Wi-Fi 6 and Bluetooth built in",
                    "PCIe 4.0 M.2 slot"],
        specs={
            "General": [("Form Factor", "Micro-ATX"), ("Chipset", "AMD B550"),
                        ("Socket", "AM4")],
            "Memory": [("Memory Type", "DDR4"), ("Memory Slots", "4"),
                       ("Maximum Memory", "128GB"), ("Memory Speed", "Up to 4400MHz")],
            "Expansion": [("PCIe x16 Slots", "1 (PCIe 4.0)"), ("M.2 Slots", "2")],
            "Connectivity": [("LAN", "1Gb Ethernet"), ("Wireless", "Wi-Fi 6"),
                             ("Rear USB", "6 ports")],
        },
        component={"slot": "motherboard", "socket": "AM4", "form_factor": "Micro-ATX",
                   "ram_type": "DDR4", "ram_slots": 4, "max_ram_gb": 128, "power_watts": 45},
    ),
    P(
        "Gigabyte B650M DS3H Micro-ATX Motherboard", "Gigabyte", "motherboard", 17900,
        model="B650M DS3H", stock=12, warranty=36,
        highlights=["AM5 socket for Ryzen 7000 and newer", "DDR5 memory",
                    "Two PCIe 4.0 M.2 slots"],
        specs={
            "General": [("Form Factor", "Micro-ATX"), ("Chipset", "AMD B650"),
                        ("Socket", "AM5")],
            "Memory": [("Memory Type", "DDR5"), ("Memory Slots", "4"),
                       ("Maximum Memory", "128GB"), ("Memory Speed", "Up to 6400MHz")],
            "Expansion": [("PCIe x16 Slots", "1 (PCIe 4.0)"), ("M.2 Slots", "2")],
            "Connectivity": [("LAN", "1Gb Ethernet"), ("Rear USB", "8 ports")],
        },
        component={"slot": "motherboard", "socket": "AM5", "form_factor": "Micro-ATX",
                   "ram_type": "DDR5", "ram_slots": 4, "max_ram_gb": 128, "power_watts": 45},
    ),
    P(
        "Asus TUF Gaming B760-PLUS WiFi ATX Motherboard", "Asus", "motherboard", 21500,
        model="TUF GAMING B760-PLUS WIFI", was=23900, stock=10, warranty=36,
        highlights=["LGA1700 socket for 12th to 14th Gen Intel", "DDR5 memory",
                    "Wi-Fi 6 and 2.5Gb Ethernet"],
        specs={
            "General": [("Form Factor", "ATX"), ("Chipset", "Intel B760"),
                        ("Socket", "LGA1700")],
            "Memory": [("Memory Type", "DDR5"), ("Memory Slots", "4"),
                       ("Maximum Memory", "128GB"), ("Memory Speed", "Up to 7200MHz")],
            "Expansion": [("PCIe x16 Slots", "1 (PCIe 5.0)"), ("M.2 Slots", "3")],
            "Connectivity": [("LAN", "2.5Gb Ethernet"), ("Wireless", "Wi-Fi 6"),
                             ("Rear USB", "8 ports")],
        },
        component={"slot": "motherboard", "socket": "LGA1700", "form_factor": "ATX",
                   "ram_type": "DDR5", "ram_slots": 4, "max_ram_gb": 128, "power_watts": 50},
    ),
    P(
        "MSI PRO H610M-E DDR4 Micro-ATX Motherboard", "MSI", "motherboard", 9800,
        model="PRO H610M-E DDR4", stock=20, warranty=36,
        highlights=["Entry-level LGA1700 board", "DDR4 memory keeps a build cheap",
                    "Compact Micro-ATX footprint"],
        specs={
            "General": [("Form Factor", "Micro-ATX"), ("Chipset", "Intel H610"),
                        ("Socket", "LGA1700")],
            "Memory": [("Memory Type", "DDR4"), ("Memory Slots", "2"),
                       ("Maximum Memory", "64GB"), ("Memory Speed", "Up to 3200MHz")],
            "Expansion": [("PCIe x16 Slots", "1 (PCIe 4.0)"), ("M.2 Slots", "1")],
            "Connectivity": [("LAN", "1Gb Ethernet"), ("Rear USB", "4 ports")],
        },
        component={"slot": "motherboard", "socket": "LGA1700", "form_factor": "Micro-ATX",
                   "ram_type": "DDR4", "ram_slots": 2, "max_ram_gb": 64, "power_watts": 40},
    ),
    P(
        "Asus ROG Strix X670E-A Gaming WiFi ATX Motherboard", "Asus", "motherboard",
        52000, model="ROG STRIX X670E-A GAMING WIFI", stock=4, warranty=36,
        highlights=["Enthusiast AM5 board", "PCIe 5.0 graphics and storage",
                    "Wi-Fi 6E and 2.5Gb Ethernet"],
        specs={
            "General": [("Form Factor", "ATX"), ("Chipset", "AMD X670E"),
                        ("Socket", "AM5")],
            "Memory": [("Memory Type", "DDR5"), ("Memory Slots", "4"),
                       ("Maximum Memory", "128GB"), ("Memory Speed", "Up to 6400MHz")],
            "Expansion": [("PCIe x16 Slots", "2 (PCIe 5.0)"), ("M.2 Slots", "4")],
            "Connectivity": [("LAN", "2.5Gb Ethernet"), ("Wireless", "Wi-Fi 6E"),
                             ("Rear USB", "12 ports")],
        },
        component={"slot": "motherboard", "socket": "AM5", "form_factor": "ATX",
                   "ram_type": "DDR5", "ram_slots": 4, "max_ram_gb": 128, "power_watts": 60},
    ),
    P(
        "Gigabyte B550I AORUS Pro AX Mini-ITX Motherboard", "Gigabyte", "motherboard",
        19500, model="B550I AORUS PRO AX", stock=6, warranty=36,
        highlights=["Mini-ITX board for a small-form-factor build",
                    "Wi-Fi 6 included", "Two DDR4 slots"],
        specs={
            "General": [("Form Factor", "Mini-ITX"), ("Chipset", "AMD B550"),
                        ("Socket", "AM4")],
            "Memory": [("Memory Type", "DDR4"), ("Memory Slots", "2"),
                       ("Maximum Memory", "64GB")],
            "Expansion": [("PCIe x16 Slots", "1 (PCIe 4.0)"), ("M.2 Slots", "2")],
            "Connectivity": [("LAN", "2.5Gb Ethernet"), ("Wireless", "Wi-Fi 6")],
        },
        component={"slot": "motherboard", "socket": "AM4", "form_factor": "Mini-ITX",
                   "ram_type": "DDR4", "ram_slots": 2, "max_ram_gb": 64, "power_watts": 40},
    ),

    # ------------------------------------------------------------------ RAM
    P(
        "Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz", "Corsair", "ram", 5900,
        model="CMK16GX4M2E3200C16", was=6800, stock=40, warranty=60, featured=True,
        highlights=["16GB kit in two matched modules", "3200MHz with XMP 2.0",
                    "Low-profile heat spreader clears most air coolers"],
        specs={
            "General": [("Type", "Desktop Memory"), ("Memory Type", "DDR4")],
            "Performance": [("Capacity", "16GB (2 x 8GB)"), ("Speed", "3200MHz"),
                            ("CAS Latency", "CL16"), ("Voltage", "1.35V")],
            "Physical": [("Heat Spreader", "Aluminium"), ("Profile", "Low profile")],
        },
        component={"slot": "ram", "ram_type": "DDR4", "capacity_gb": 16,
                   "module_count": 2, "power_watts": 8},
    ),
    P(
        "Kingston FURY Beast 32GB (2x16GB) DDR5 5600MHz", "Kingston", "ram", 15900,
        model="KF556C40BBK2-32", stock=18, warranty=60,
        highlights=["32GB DDR5 kit", "5600MHz with a single BIOS toggle",
                    "Plug-and-play on both Intel and AMD"],
        specs={
            "General": [("Type", "Desktop Memory"), ("Memory Type", "DDR5")],
            "Performance": [("Capacity", "32GB (2 x 16GB)"), ("Speed", "5600MHz"),
                            ("CAS Latency", "CL40"), ("Voltage", "1.25V")],
            "Physical": [("Heat Spreader", "Aluminium")],
        },
        component={"slot": "ram", "ram_type": "DDR5", "capacity_gb": 32,
                   "module_count": 2, "power_watts": 10},
    ),
    P(
        "Corsair Vengeance 32GB (2x16GB) DDR5 6000MHz", "Corsair", "ram", 19500,
        model="CMK32GX5M2B6000C36", was=21500, stock=11, warranty=60,
        highlights=["6000MHz DDR5, the sweet spot for a Ryzen 7000 build",
                    "32GB across two modules", "On-die ECC"],
        specs={
            "General": [("Type", "Desktop Memory"), ("Memory Type", "DDR5")],
            "Performance": [("Capacity", "32GB (2 x 16GB)"), ("Speed", "6000MHz"),
                            ("CAS Latency", "CL36"), ("Voltage", "1.35V")],
            "Physical": [("Heat Spreader", "Aluminium")],
        },
        component={"slot": "ram", "ram_type": "DDR5", "capacity_gb": 32,
                   "module_count": 2, "power_watts": 10},
    ),
    P(
        "Kingston FURY Beast 8GB DDR4 3200MHz", "Kingston", "ram", 2950,
        model="KF432C16BB/8", stock=52, warranty=60,
        highlights=["Single 8GB module", "3200MHz", "Handy for a second-hand upgrade"],
        specs={
            "General": [("Type", "Desktop Memory"), ("Memory Type", "DDR4")],
            "Performance": [("Capacity", "8GB (1 x 8GB)"), ("Speed", "3200MHz"),
                            ("CAS Latency", "CL16")],
        },
        component={"slot": "ram", "ram_type": "DDR4", "capacity_gb": 8,
                   "module_count": 1, "power_watts": 5},
    ),

    # -------------------------------------------------------- Graphics card
    P(
        "NVIDIA GeForce RTX 4060 8GB Graphics Card", "NVIDIA", "graphics-card", 38500,
        model="RTX4060-8G", was=42000, stock=13, warranty=36, featured=True,
        highlights=["Comfortable 1080p gaming with ray tracing",
                    "8GB GDDR6 memory", "Modest power draw for a small build"],
        specs={
            "General": [("Chipset", "NVIDIA GeForce RTX 4060"),
                        ("Architecture", "Ada Lovelace")],
            "Memory": [("Memory Size", "8GB"), ("Memory Type", "GDDR6"),
                       ("Memory Bus", "128-bit")],
            "Performance": [("Boost Clock", "2460MHz"), ("CUDA Cores", "3072")],
            "Display": [("Outputs", "3 x DisplayPort 1.4a, 1 x HDMI 2.1"),
                        ("Maximum Resolution", "7680 x 4320")],
            "Power": [("Power Draw", "115W"), ("Recommended PSU", "550W"),
                      ("Power Connector", "1 x 8-pin")],
            "Physical": [("Length", "245mm"), ("Slot Width", "2 slots")],
        },
        component={"slot": "gpu", "power_watts": 115, "length_mm": 245},
    ),
    P(
        "NVIDIA GeForce RTX 4070 Super 12GB Graphics Card", "NVIDIA", "graphics-card",
        78000, model="RTX4070S-12G", was=84000, stock=6, warranty=36,
        highlights=["Built for high-refresh 1440p", "12GB GDDR6X memory",
                    "Strong ray-tracing performance"],
        specs={
            "General": [("Chipset", "NVIDIA GeForce RTX 4070 Super"),
                        ("Architecture", "Ada Lovelace")],
            "Memory": [("Memory Size", "12GB"), ("Memory Type", "GDDR6X"),
                       ("Memory Bus", "192-bit")],
            "Performance": [("Boost Clock", "2475MHz"), ("CUDA Cores", "7168")],
            "Display": [("Outputs", "3 x DisplayPort 1.4a, 1 x HDMI 2.1")],
            "Power": [("Power Draw", "220W"), ("Recommended PSU", "700W"),
                      ("Power Connector", "1 x 16-pin")],
            "Physical": [("Length", "305mm"), ("Slot Width", "2.5 slots")],
        },
        component={"slot": "gpu", "power_watts": 220, "length_mm": 305},
    ),
    P(
        "MSI GeForce RTX 4060 Ti Ventus 2X 8GB", "MSI", "graphics-card", 52000,
        model="RTX 4060 Ti VENTUS 2X BLACK 8G OC", stock=8, warranty=36,
        highlights=["Dual-fan cooler that stays quiet", "8GB GDDR6",
                    "Good 1440p performance at sensible power"],
        specs={
            "General": [("Chipset", "NVIDIA GeForce RTX 4060 Ti"),
                        ("Architecture", "Ada Lovelace")],
            "Memory": [("Memory Size", "8GB"), ("Memory Type", "GDDR6"),
                       ("Memory Bus", "128-bit")],
            "Performance": [("Boost Clock", "2565MHz"), ("CUDA Cores", "4352")],
            "Power": [("Power Draw", "160W"), ("Recommended PSU", "600W")],
            "Physical": [("Length", "199mm"), ("Slot Width", "2 slots")],
        },
        component={"slot": "gpu", "power_watts": 160, "length_mm": 199},
    ),
    P(
        "Asus Dual Radeon RX 7600 8GB OC Edition", "Asus", "graphics-card", 34500,
        model="DUAL-RX7600-O8G", was=37500, stock=10, warranty=36,
        highlights=["Solid 1080p card at a keen price", "8GB GDDR6",
                    "Compact two-slot cooler"],
        specs={
            "General": [("Chipset", "AMD Radeon RX 7600"), ("Architecture", "RDNA 3")],
            "Memory": [("Memory Size", "8GB"), ("Memory Type", "GDDR6"),
                       ("Memory Bus", "128-bit")],
            "Performance": [("Boost Clock", "2755MHz"), ("Stream Processors", "2048")],
            "Power": [("Power Draw", "165W"), ("Recommended PSU", "550W")],
            "Physical": [("Length", "204mm"), ("Slot Width", "2 slots")],
        },
        component={"slot": "gpu", "power_watts": 165, "length_mm": 204},
    ),
    P(
        "Gigabyte GeForce RTX 4090 Gaming OC 24GB", "Gigabyte", "graphics-card",
        265000, model="GV-N4090GAMING OC-24GD", stock=2, warranty=36,
        highlights=["Flagship card for 4K and heavy rendering",
                    "24GB GDDR6X memory", "Needs a large case and a big power supply"],
        specs={
            "General": [("Chipset", "NVIDIA GeForce RTX 4090"),
                        ("Architecture", "Ada Lovelace")],
            "Memory": [("Memory Size", "24GB"), ("Memory Type", "GDDR6X"),
                       ("Memory Bus", "384-bit")],
            "Performance": [("Boost Clock", "2535MHz"), ("CUDA Cores", "16384")],
            "Power": [("Power Draw", "450W"), ("Recommended PSU", "1000W")],
            "Physical": [("Length", "340mm"), ("Slot Width", "3.5 slots")],
        },
        component={"slot": "gpu", "power_watts": 450, "length_mm": 340},
    ),

    # ------------------------------------------------------------------ SSD
    P(
        "Samsung 980 500GB NVMe M.2 SSD", "Samsung", "ssd", 5900,
        model="MZ-V8V500BW", was=6900, stock=45, warranty=60, featured=True,
        highlights=["Boot drive that makes an old machine feel new",
                    "Up to 3,100 MB/s sequential read", "Five-year warranty"],
        specs={
            "General": [("Type", "Internal SSD"), ("Form Factor", "M.2 2280"),
                        ("Interface", "PCIe 3.0 x4 NVMe")],
            "Performance": [("Capacity", "500GB"), ("Sequential Read", "3100 MB/s"),
                            ("Sequential Write", "2600 MB/s")],
            "Endurance": [("TBW", "300TB"), ("MTBF", "1.5 million hours")],
        },
        component={"slot": "ssd", "capacity_gb": 500, "power_watts": 6},
    ),
    P(
        "Samsung 990 PRO 1TB NVMe M.2 SSD", "Samsung", "ssd", 14500,
        model="MZ-V9P1T0BW", stock=20, warranty=60,
        highlights=["PCIe 4.0 speeds up to 7,450 MB/s",
                    "Heat-managed for sustained transfers", "1TB capacity"],
        specs={
            "General": [("Type", "Internal SSD"), ("Form Factor", "M.2 2280"),
                        ("Interface", "PCIe 4.0 x4 NVMe")],
            "Performance": [("Capacity", "1TB"), ("Sequential Read", "7450 MB/s"),
                            ("Sequential Write", "6900 MB/s"),
                            ("Random Read", "1,200K IOPS")],
            "Endurance": [("TBW", "600TB")],
        },
        component={"slot": "ssd", "capacity_gb": 1000, "power_watts": 8},
    ),
    P(
        "Western Digital Blue SN580 1TB NVMe SSD", "Western Digital", "ssd", 9500,
        model="WDS100T3B0E", was=10900, stock=26, warranty=60,
        highlights=["PCIe 4.0 drive at a mid-range price", "1TB capacity",
                    "Low power draw suits laptops"],
        specs={
            "General": [("Type", "Internal SSD"), ("Form Factor", "M.2 2280"),
                        ("Interface", "PCIe 4.0 x4 NVMe")],
            "Performance": [("Capacity", "1TB"), ("Sequential Read", "4150 MB/s"),
                            ("Sequential Write", "4150 MB/s")],
            "Endurance": [("TBW", "600TB")],
        },
        component={"slot": "ssd", "capacity_gb": 1000, "power_watts": 5},
    ),
    P(
        "Kingston A400 480GB SATA SSD", "Kingston", "ssd", 3900,
        model="SA400S37/480G", stock=60, warranty=36,
        highlights=["2.5-inch SATA drive for older machines",
                    "Up to 500 MB/s read", "Simple, reliable upgrade"],
        specs={
            "General": [("Type", "Internal SSD"), ("Form Factor", "2.5 inch"),
                        ("Interface", "SATA III")],
            "Performance": [("Capacity", "480GB"), ("Sequential Read", "500 MB/s"),
                            ("Sequential Write", "450 MB/s")],
        },
        component={"slot": "ssd", "capacity_gb": 480, "power_watts": 3},
    ),

    # ------------------------------------------------------------------ HDD
    P(
        "Seagate BarraCuda 2TB 3.5\" Desktop Hard Drive", "Seagate",
        "hard-disk-drive", 6200, model="ST2000DM008", was=6900, stock=32, warranty=24,
        highlights=["2TB of bulk storage", "7200 RPM", "Good companion to a small SSD"],
        specs={
            "General": [("Type", "Internal Hard Drive"), ("Form Factor", "3.5 inch"),
                        ("Interface", "SATA III")],
            "Performance": [("Capacity", "2TB"), ("Rotational Speed", "7200 RPM"),
                            ("Cache", "256MB")],
        },
        component={"slot": "hdd", "capacity_gb": 2000, "power_watts": 12},
    ),
    P(
        "Western Digital Blue 4TB Desktop Hard Drive", "Western Digital",
        "hard-disk-drive", 11500, model="WD40EZAZ", stock=14, warranty=24,
        highlights=["4TB for archives and media libraries", "5400 RPM, runs cool",
                    "SATA III interface"],
        specs={
            "General": [("Type", "Internal Hard Drive"), ("Form Factor", "3.5 inch"),
                        ("Interface", "SATA III")],
            "Performance": [("Capacity", "4TB"), ("Rotational Speed", "5400 RPM"),
                            ("Cache", "256MB")],
        },
        component={"slot": "hdd", "capacity_gb": 4000, "power_watts": 10},
    ),

    # ---------------------------------------------------------- Power supply
    P(
        "Corsair CV650 650W 80+ Bronze Power Supply", "Corsair", "power-supply", 7500,
        model="CP-9020236-UK", was=8500, stock=22, warranty=36,
        highlights=["650W, enough for most single-GPU builds",
                    "80 PLUS Bronze efficiency", "Quiet 120mm fan"],
        specs={
            "General": [("Type", "ATX Power Supply"), ("Form Factor", "ATX")],
            "Power": [("Wattage", "650W"), ("Efficiency", "80 PLUS Bronze"),
                      ("Modularity", "Non-modular")],
            "Connectors": [("PCIe", "2 x 6+2 pin"), ("SATA", "6"),
                           ("EPS", "1 x 4+4 pin")],
        },
        component={"slot": "psu", "wattage": 650, "efficiency_rating": "80+ Bronze",
                   "form_factor": "ATX"},
    ),
    P(
        "Corsair RM850e 850W 80+ Gold Fully Modular PSU", "Corsair", "power-supply",
        15900, model="CP-9020263-UK", stock=11, warranty=84,
        highlights=["850W with room for a high-end card",
                    "80 PLUS Gold efficiency", "Fully modular cabling"],
        specs={
            "General": [("Type", "ATX Power Supply"), ("Form Factor", "ATX")],
            "Power": [("Wattage", "850W"), ("Efficiency", "80 PLUS Gold"),
                      ("Modularity", "Fully modular")],
            "Connectors": [("PCIe", "4 x 6+2 pin, 1 x 12VHPWR"), ("SATA", "8")],
        },
        component={"slot": "psu", "wattage": 850, "efficiency_rating": "80+ Gold",
                   "form_factor": "ATX"},
    ),
    P(
        "Thermaltake Smart 500W 80+ White Power Supply", "Thermaltake",
        "power-supply", 4500, model="PS-SPD-0500NPCWBZ-W", stock=28, warranty=36,
        highlights=["500W for an office or entry gaming build",
                    "80 PLUS White certified", "Straightforward and inexpensive"],
        specs={
            "General": [("Type", "ATX Power Supply"), ("Form Factor", "ATX")],
            "Power": [("Wattage", "500W"), ("Efficiency", "80 PLUS White"),
                      ("Modularity", "Non-modular")],
            "Connectors": [("PCIe", "1 x 6+2 pin"), ("SATA", "4")],
        },
        component={"slot": "psu", "wattage": 500, "efficiency_rating": "80+ White",
                   "form_factor": "ATX"},
    ),
    P(
        "Cooler Master MWE Gold 1050 V2 Full Modular PSU", "Cooler Master",
        "power-supply", 24500, model="MPE-A501-AFCAG-3EU", stock=5, warranty=120,
        highlights=["1050W for a flagship graphics card",
                    "80 PLUS Gold", "Ten-year warranty"],
        specs={
            "General": [("Type", "ATX Power Supply"), ("Form Factor", "ATX")],
            "Power": [("Wattage", "1050W"), ("Efficiency", "80 PLUS Gold"),
                      ("Modularity", "Fully modular")],
            "Connectors": [("PCIe", "6 x 6+2 pin, 1 x 12VHPWR"), ("SATA", "12")],
        },
        component={"slot": "psu", "wattage": 1050, "efficiency_rating": "80+ Gold",
                   "form_factor": "ATX"},
    ),

    # -------------------------------------------------------------- PC case
    P(
        "Cooler Master MasterBox Q300L Micro-ATX Case", "Cooler Master", "pc-case",
        5500, model="MCB-Q300L-KANN-S00", was=6200, stock=18, warranty=12,
        highlights=["Compact Micro-ATX case with a mesh front",
                    "Magnetic dust filters", "Takes cards up to 360mm"],
        specs={
            "General": [("Type", "Micro-ATX Case"), ("Colour", "Black"),
                        ("Side Panel", "Acrylic")],
            "Compatibility": [("Motherboard Support", "Micro-ATX, Mini-ITX"),
                              ("Maximum GPU Length", "360mm"),
                              ("Maximum Cooler Height", "159mm")],
            "Cooling": [("Included Fans", "1 x 120mm"), ("Fan Mounts", "4")],
            "Drive Bays": [("2.5 inch", "2"), ("3.5 inch", "2")],
        },
        component={"slot": "case", "supported_form_factors": ["Micro-ATX", "Mini-ITX"],
                   "max_gpu_length_mm": 360, "max_cooler_height_mm": 159},
    ),
    P(
        "Corsair 4000D Airflow ATX Mid-Tower Case", "Corsair", "pc-case", 11500,
        model="CC-9011200-WW", stock=14, warranty=24, featured=True,
        highlights=["High-airflow front panel", "Tempered glass side",
                    "Genuinely easy to build in"],
        specs={
            "General": [("Type", "ATX Mid Tower"), ("Colour", "Black"),
                        ("Side Panel", "Tempered glass")],
            "Compatibility": [("Motherboard Support", "ATX, Micro-ATX, Mini-ITX"),
                              ("Maximum GPU Length", "360mm"),
                              ("Maximum Cooler Height", "170mm")],
            "Cooling": [("Included Fans", "2 x 120mm"),
                        ("Radiator Support", "Up to 360mm front")],
            "Drive Bays": [("2.5 inch", "2"), ("3.5 inch", "2")],
        },
        component={"slot": "case", "supported_form_factors": ["ATX", "Micro-ATX", "Mini-ITX"],
                   "max_gpu_length_mm": 360, "max_cooler_height_mm": 170},
    ),
    P(
        "Thermaltake Versa H18 Mini-ITX Case", "Thermaltake", "pc-case", 4200,
        model="CA-1J4-00S1NN-A1", stock=16, warranty=12,
        highlights=["Small case for a compact build", "Tempered glass window",
                    "Fits cards up to 350mm"],
        specs={
            "General": [("Type", "Mini Tower"), ("Colour", "Black"),
                        ("Side Panel", "Tempered glass")],
            "Compatibility": [("Motherboard Support", "Micro-ATX, Mini-ITX"),
                              ("Maximum GPU Length", "350mm"),
                              ("Maximum Cooler Height", "155mm")],
            "Cooling": [("Included Fans", "1 x 120mm")],
        },
        component={"slot": "case", "supported_form_factors": ["Micro-ATX", "Mini-ITX"],
                   "max_gpu_length_mm": 350, "max_cooler_height_mm": 155},
    ),
    P(
        "Asus TUF Gaming GT301 ATX Mid-Tower Case", "Asus", "pc-case", 9800,
        model="GT301 TUF GAMING CASE", was=11000, stock=9, warranty=24,
        highlights=["Three ARGB fans included", "Headset hook on the roof",
                    "Steel mesh front for airflow"],
        specs={
            "General": [("Type", "ATX Mid Tower"), ("Colour", "Black"),
                        ("Side Panel", "Tempered glass")],
            "Compatibility": [("Motherboard Support", "ATX, Micro-ATX, Mini-ITX"),
                              ("Maximum GPU Length", "320mm"),
                              ("Maximum Cooler Height", "160mm")],
            "Cooling": [("Included Fans", "3 x 120mm ARGB")],
        },
        component={"slot": "case", "supported_form_factors": ["ATX", "Micro-ATX", "Mini-ITX"],
                   "max_gpu_length_mm": 320, "max_cooler_height_mm": 160},
    ),

    # -------------------------------------------------------------- Laptops
    P(
        "Asus TUF Gaming F15 FX507ZC4", "Asus", "gaming-laptop", 118000,
        model="FX507ZC4-HN109W", was=129000, stock=8, warranty=24, featured=True,
        highlights=["144Hz display for fast-paced games",
                    "RTX 3050 graphics with a 12th Gen Core i5",
                    "Military-grade durability testing"],
        specs={
            "General": [("Type", "Gaming Laptop"), ("Operating System", "Windows 11 Home"),
                        ("Colour", "Graphite Black")],
            "Performance": [("Processor", "Intel Core i5-12500H"), ("Cores", "12"),
                            ("RAM", "16GB DDR4 3200MHz"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "NVIDIA GeForce RTX 3050 4GB")],
            "Display": [("Size", "15.6 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS"), ("Refresh Rate", "144Hz")],
            "Connectivity": [("Wireless", "Wi-Fi 6"), ("Bluetooth", "5.2"),
                             ("Ports", "3 x USB-A, 1 x USB-C, HDMI 2.0b, RJ45")],
            "Battery": [("Capacity", "56Wh"), ("Adapter", "180W")],
            "Physical": [("Weight", "2.2 kg"), ("Thickness", "24.9mm")],
        },
        variants=[("16-512", "16GB / 512GB", 118000, 129000, 8, 2200),
                  ("16-1TB", "16GB / 1TB", 128000, 138000, 5, 2200)],
    ),
    P(
        "Lenovo IdeaPad Slim 3 15IAU7", "Lenovo", "ultrabook", 62000,
        model="82RK00XKIN", was=68000, stock=12, warranty=24,
        highlights=["Light enough to carry all day",
                    "12th Gen Core i3 for study and office work",
                    "Full-size keyboard with a number pad"],
        specs={
            "General": [("Type", "Thin & Light Laptop"),
                        ("Operating System", "Windows 11 Home"), ("Colour", "Arctic Grey")],
            "Performance": [("Processor", "Intel Core i3-1215U"), ("Cores", "6"),
                            ("RAM", "8GB LPDDR5"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "Intel UHD Graphics")],
            "Display": [("Size", "15.6 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "TN"), ("Refresh Rate", "60Hz")],
            "Connectivity": [("Wireless", "Wi-Fi 6"), ("Bluetooth", "5.1")],
            "Battery": [("Capacity", "45Wh"), ("Rated Life", "Up to 7 hours")],
            "Physical": [("Weight", "1.62 kg")],
        },
        variants=[("8-512", "8GB / 512GB", 62000, 68000, 12, 1620),
                  ("16-512", "16GB / 512GB", 72000, 78000, 6, 1620)],
    ),
    P(
        "HP Pavilion x360 14-ek1010TU", "HP", "ultrabook", 89000,
        model="14-EK1010TU", was=95000, stock=7, warranty=24,
        highlights=["Screen folds all the way back into a tablet",
                    "Touch display with pen support",
                    "13th Gen Core i5"],
        specs={
            "General": [("Type", "2-in-1 Convertible"),
                        ("Operating System", "Windows 11 Home"), ("Colour", "Natural Silver")],
            "Performance": [("Processor", "Intel Core i5-1335U"), ("Cores", "10"),
                            ("RAM", "16GB DDR4"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "Intel Iris Xe")],
            "Display": [("Size", "14 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS Touch"), ("Refresh Rate", "60Hz")],
            "Connectivity": [("Wireless", "Wi-Fi 6E"), ("Bluetooth", "5.3")],
            "Battery": [("Capacity", "43Wh"), ("Fast Charge", "50% in 45 minutes")],
            "Physical": [("Weight", "1.52 kg")],
        },
    ),
    P(
        "Apple MacBook Air 13 M2", "Apple", "ultrabook", 148000,
        model="MLY33", stock=6, warranty=12, featured=True,
        highlights=["Silent, fanless design",
                    "Up to 18 hours of battery life",
                    "Liquid Retina display"],
        specs={
            "General": [("Type", "Thin & Light Laptop"), ("Operating System", "macOS"),
                        ("Colour", "Midnight")],
            "Performance": [("Processor", "Apple M2"), ("Cores", "8"),
                            ("RAM", "8GB Unified Memory"), ("Storage", "256GB SSD"),
                            ("Graphics", "8-core GPU")],
            "Display": [("Size", "13.6 inch"), ("Resolution", "2560 x 1664"),
                        ("Panel Type", "Liquid Retina IPS"), ("Brightness", "500 nits")],
            "Connectivity": [("Wireless", "Wi-Fi 6"), ("Ports", "2 x Thunderbolt, MagSafe 3")],
            "Battery": [("Rated Life", "Up to 18 hours")],
            "Physical": [("Weight", "1.24 kg")],
        },
        variants=[("8-256", "8GB / 256GB", 148000, None, 6, 1240),
                  ("16-512", "16GB / 512GB", 189000, 198000, 3, 1240)],
    ),
    P(
        "Dell Latitude 3540 Business Laptop", "Dell", "business-laptop", 105000,
        model="LAT-3540-I5", stock=9, warranty=36,
        highlights=["Built for a three-year office life",
                    "Spill-resistant keyboard",
                    "Three-year onsite warranty"],
        specs={
            "General": [("Type", "Business Laptop"),
                        ("Operating System", "Windows 11 Pro"), ("Colour", "Grey")],
            "Performance": [("Processor", "Intel Core i5-1335U"),
                            ("RAM", "16GB DDR4"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "Intel Iris Xe")],
            "Display": [("Size", "15.6 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS"), ("Finish", "Anti-glare")],
            "Security": [("Fingerprint Reader", "Yes"), ("TPM", "TPM 2.0")],
            "Physical": [("Weight", "1.83 kg")],
        },
    ),
    P(
        "Acer Nitro V 15 ANV15-51", "Acer", "gaming-laptop", 132000,
        model="ANV15-51-56J1", was=142000, stock=5, warranty=24,
        highlights=["RTX 4050 graphics", "165Hz screen",
                    "Dual-fan cooling with a dedicated boost key"],
        specs={
            "General": [("Type", "Gaming Laptop"), ("Operating System", "Windows 11 Home")],
            "Performance": [("Processor", "Intel Core i5-13420H"),
                            ("RAM", "16GB DDR5"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "NVIDIA GeForce RTX 4050 6GB")],
            "Display": [("Size", "15.6 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS"), ("Refresh Rate", "165Hz")],
            "Battery": [("Capacity", "57Wh"), ("Adapter", "180W")],
            "Physical": [("Weight", "2.1 kg")],
        },
    ),
    P(
        "Asus Vivobook 15 X1502ZA", "Asus", "ultrabook", 74500,
        model="X1502ZA-EJ1426W", was=79000, stock=15, warranty=24,
        highlights=["Big 15.6-inch screen at a student price",
                    "Backlit keyboard", "Fingerprint unlock"],
        specs={
            "General": [("Type", "Thin & Light Laptop"),
                        ("Operating System", "Windows 11 Home")],
            "Performance": [("Processor", "Intel Core i5-1235U"),
                            ("RAM", "8GB DDR4"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "Intel Iris Xe")],
            "Display": [("Size", "15.6 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS")],
            "Physical": [("Weight", "1.7 kg")],
        },
    ),
    P(
        "Lenovo ThinkPad E14 Gen 5", "Lenovo", "business-laptop", 122000,
        model="21JK0055IN", stock=6, warranty=36,
        highlights=["The keyboard ThinkPads are bought for",
                    "Ryzen 5 7530U", "Physical webcam shutter"],
        specs={
            "General": [("Type", "Business Laptop"),
                        ("Operating System", "Windows 11 Pro")],
            "Performance": [("Processor", "AMD Ryzen 5 7530U"),
                            ("RAM", "16GB DDR4"), ("Storage", "512GB PCIe SSD"),
                            ("Graphics", "AMD Radeon Graphics")],
            "Display": [("Size", "14 inch"), ("Resolution", "1920 x 1200"),
                        ("Panel Type", "IPS"), ("Aspect Ratio", "16:10")],
            "Security": [("Fingerprint Reader", "Yes"), ("Webcam Shutter", "Yes")],
            "Physical": [("Weight", "1.41 kg")],
        },
    ),

    # ------------------------------------------------------------- Desktops
    P(
        "MicroMart Vanguard R5 Gaming PC", "AMD", "gaming-pc", 92000,
        model="TT-VANGUARD-R5", was=99000, stock=6, warranty=24, featured=True,
        highlights=["Assembled, cabled and stress-tested before it ships",
                    "Ryzen 5 5600X with an RTX 4060",
                    "One-year onsite support inside Dhaka"],
        specs={
            "General": [("Type", "Gaming Desktop"),
                        ("Operating System", "Windows 11 Home"), ("Case", "Mid tower")],
            "Performance": [("Processor", "AMD Ryzen 5 5600X"),
                            ("RAM", "16GB DDR4 3200MHz"), ("Storage", "1TB NVMe SSD"),
                            ("Graphics", "NVIDIA GeForce RTX 4060 8GB")],
            "Power": [("Power Supply", "650W 80+ Bronze")],
            "Connectivity": [("LAN", "1Gb Ethernet"), ("Wireless", "Wi-Fi 6")],
        },
    ),
    P(
        "MicroMart Studio i7 Workstation", "Intel", "office-desktop", 138000,
        model="TT-STUDIO-I7", stock=4, warranty=24,
        highlights=["Built for editing and rendering",
                    "32GB of memory as standard",
                    "Quiet under sustained load"],
        specs={
            "General": [("Type", "Workstation"),
                        ("Operating System", "Windows 11 Pro"), ("Case", "Mid tower")],
            "Performance": [("Processor", "Intel Core i7-13700K"),
                            ("RAM", "32GB DDR5 5600MHz"), ("Storage", "2TB NVMe SSD"),
                            ("Graphics", "NVIDIA GeForce RTX 4070 Super 12GB")],
            "Power": [("Power Supply", "850W 80+ Gold")],
        },
    ),
    P(
        "MicroMart Office Pro Mini Desktop", "Intel", "office-desktop", 46500,
        model="TT-OFFICE-MINI", was=51000, stock=14, warranty=24,
        highlights=["Small enough to sit behind a monitor",
                    "Boots in seconds from an NVMe drive",
                    "Ideal for reception desks and study rooms"],
        specs={
            "General": [("Type", "Mini Desktop"),
                        ("Operating System", "Windows 11 Home")],
            "Performance": [("Processor", "Intel Core i3-12100"),
                            ("RAM", "8GB DDR4"), ("Storage", "512GB NVMe SSD"),
                            ("Graphics", "Intel UHD 730")],
            "Connectivity": [("Ports", "4 x USB-A, HDMI, DisplayPort, RJ45")],
        },
    ),
    P(
        "HP All-in-One 24-cb1004in", "HP", "all-in-one-pc", 88000,
        model="24-CB1004IN", stock=5, warranty=12,
        highlights=["Everything behind a 23.8-inch screen",
                    "Wireless keyboard and mouse included",
                    "Pop-up privacy camera"],
        specs={
            "General": [("Type", "All-in-One PC"),
                        ("Operating System", "Windows 11 Home")],
            "Performance": [("Processor", "Intel Core i3-1215U"),
                            ("RAM", "8GB DDR4"), ("Storage", "512GB SSD"),
                            ("Graphics", "Intel UHD Graphics")],
            "Display": [("Size", "23.8 inch"), ("Resolution", "1920 x 1080"),
                        ("Panel Type", "IPS")],
        },
    ),

    # ------------------------------------------------------------- Monitors
    P(
        "LG UltraGear 27GP850-B 27\" QHD Gaming Monitor", "LG", "gaming-monitor",
        62000, model="27GP850-B", was=68000, stock=7, warranty=36, featured=True,
        highlights=["165Hz Nano IPS panel, overclockable to 180Hz",
                    "1ms grey-to-grey response",
                    "Height, tilt and pivot adjustment"],
        specs={
            "General": [("Type", "Gaming Monitor"), ("Screen Size", "27 inch")],
            "Display": [("Resolution", "2560 x 1440"), ("Panel Type", "Nano IPS"),
                        ("Refresh Rate", "165Hz"), ("Response Time", "1ms GtG"),
                        ("Brightness", "400 nits"), ("Contrast Ratio", "1000:1")],
            "Colour": [("Colour Gamut", "98% DCI-P3"), ("HDR", "HDR10")],
            "Connectivity": [("HDMI", "2 x HDMI 2.0"), ("DisplayPort", "1 x DP 1.4"),
                             ("USB Hub", "2 x USB 3.0")],
            "Ergonomics": [("Height Adjust", "110mm"), ("Pivot", "Yes"),
                           ("VESA Mount", "100 x 100mm")],
        },
        component={"slot": "monitor", "power_watts": 45},
    ),
    P(
        "Asus TUF Gaming VG249Q1A 24\" 165Hz Monitor", "Asus", "gaming-monitor",
        24500, model="VG249Q1A", was=27000, stock=16, warranty=36,
        highlights=["165Hz on a 24-inch IPS panel",
                    "FreeSync Premium", "Built-in speakers"],
        specs={
            "General": [("Type", "Gaming Monitor"), ("Screen Size", "23.8 inch")],
            "Display": [("Resolution", "1920 x 1080"), ("Panel Type", "IPS"),
                        ("Refresh Rate", "165Hz"), ("Response Time", "1ms MPRT"),
                        ("Brightness", "250 nits")],
            "Connectivity": [("HDMI", "2 x HDMI 1.4"), ("DisplayPort", "1 x DP 1.2")],
            "Ergonomics": [("Tilt", "Yes"), ("VESA Mount", "100 x 100mm")],
        },
        component={"slot": "monitor", "power_watts": 30},
    ),
    P(
        "Dell P2422H 24\" Professional Monitor", "Dell", "office-monitor", 28500,
        model="P2422H", stock=13, warranty=36,
        highlights=["Comfortable for a full working day",
                    "Height, swivel, tilt and pivot", "Three-year exchange warranty"],
        specs={
            "General": [("Type", "Office Monitor"), ("Screen Size", "23.8 inch")],
            "Display": [("Resolution", "1920 x 1080"), ("Panel Type", "IPS"),
                        ("Refresh Rate", "60Hz"), ("Brightness", "250 nits")],
            "Connectivity": [("HDMI", "1 x HDMI 1.4"), ("DisplayPort", "1 x DP 1.2"),
                             ("VGA", "1"), ("USB Hub", "4 x USB 3.2")],
            "Ergonomics": [("Height Adjust", "150mm"), ("Pivot", "Yes")],
        },
        component={"slot": "monitor", "power_watts": 25},
    ),
    P(
        "BenQ GW2480 24\" Eye-Care Monitor", "BenQ", "office-monitor", 19500,
        model="GW2480", was=21500, stock=20, warranty=36,
        highlights=["Flicker-free with a low blue-light mode",
                    "Ultra-slim bezels", "Brightness adapts to the room"],
        specs={
            "General": [("Type", "Office Monitor"), ("Screen Size", "23.8 inch")],
            "Display": [("Resolution", "1920 x 1080"), ("Panel Type", "IPS"),
                        ("Refresh Rate", "60Hz"), ("Brightness", "250 nits")],
            "Connectivity": [("HDMI", "1"), ("DisplayPort", "1"), ("VGA", "1")],
        },
        component={"slot": "monitor", "power_watts": 22},
    ),
    P(
        "Samsung Odyssey G5 32\" Curved QHD Monitor", "Samsung", "gaming-monitor",
        44500, model="LC32G55TQWWXXL", stock=6, warranty=24,
        highlights=["1000R curve wraps around your view",
                    "144Hz at 1440p", "HDR10 support"],
        specs={
            "General": [("Type", "Gaming Monitor"), ("Screen Size", "32 inch")],
            "Display": [("Resolution", "2560 x 1440"), ("Panel Type", "VA Curved"),
                        ("Refresh Rate", "144Hz"), ("Response Time", "1ms MPRT"),
                        ("Curvature", "1000R"), ("Contrast Ratio", "2500:1")],
            "Connectivity": [("HDMI", "1 x HDMI 2.0"), ("DisplayPort", "1 x DP 1.2")],
        },
        component={"slot": "monitor", "power_watts": 50},
    ),

    # ---------------------------------------------------------- Mobile phone
    P(
        "Samsung Galaxy S24 5G", "Samsung", "mobile-phone", 112000,
        model="SM-S921B", was=125000, stock=9, warranty=12, featured=True,
        highlights=["Bright 120Hz display readable in sunlight",
                    "Triple camera with 3x optical zoom",
                    "Seven years of software updates"],
        specs={
            "General": [("Type", "Smartphone"), ("Operating System", "Android 14"),
                        ("SIM", "Dual SIM (nano + eSIM)")],
            "Display": [("Size", "6.2 inch"), ("Resolution", "2340 x 1080"),
                        ("Panel Type", "Dynamic AMOLED 2X"), ("Refresh Rate", "120Hz")],
            "Performance": [("Processor", "Exynos 2400"), ("RAM", "8GB"),
                            ("Storage", "256GB")],
            "Camera": [("Main Camera", "50MP OIS"), ("Ultra-wide", "12MP"),
                       ("Telephoto", "10MP 3x"), ("Front Camera", "12MP")],
            "Battery": [("Capacity", "4000mAh"), ("Charging", "25W wired, 15W wireless")],
        },
        variants=[("8-256", "8GB / 256GB", 112000, 125000, 9, 168),
                  ("8-512", "8GB / 512GB", 124000, 136000, 4, 168)],
    ),
    P(
        "Xiaomi Redmi Note 13 Pro", "Xiaomi", "mobile-phone", 34500,
        model="2312DRA50G", was=38000, stock=22, warranty=12,
        highlights=["200MP main camera", "120Hz AMOLED screen",
                    "67W charging fills it in about 45 minutes"],
        specs={
            "General": [("Type", "Smartphone"), ("Operating System", "Android 13")],
            "Display": [("Size", "6.67 inch"), ("Resolution", "2712 x 1220"),
                        ("Panel Type", "AMOLED"), ("Refresh Rate", "120Hz")],
            "Performance": [("Processor", "Snapdragon 7s Gen 2"), ("RAM", "8GB"),
                            ("Storage", "256GB")],
            "Camera": [("Main Camera", "200MP OIS"), ("Ultra-wide", "8MP"),
                       ("Front Camera", "16MP")],
            "Battery": [("Capacity", "5100mAh"), ("Charging", "67W")],
        },
        variants=[("8-256", "8GB / 256GB", 34500, 38000, 22, 187),
                  ("12-512", "12GB / 512GB", 42000, 45000, 8, 187)],
    ),
    P(
        "Realme 12 Pro 5G", "Realme", "mobile-phone", 39500,
        model="RMX3842", stock=14, warranty=12,
        highlights=["Periscope-style portrait telephoto",
                    "Curved 120Hz display", "5000mAh battery"],
        specs={
            "General": [("Type", "Smartphone"), ("Operating System", "Android 14")],
            "Display": [("Size", "6.7 inch"), ("Resolution", "2412 x 1080"),
                        ("Panel Type", "AMOLED Curved"), ("Refresh Rate", "120Hz")],
            "Performance": [("Processor", "Snapdragon 6 Gen 1"), ("RAM", "8GB"),
                            ("Storage", "256GB")],
            "Camera": [("Main Camera", "50MP OIS"), ("Telephoto", "32MP 2x"),
                       ("Front Camera", "16MP")],
            "Battery": [("Capacity", "5000mAh"), ("Charging", "67W")],
        },
    ),
    P(
        "Samsung Galaxy A15 4G", "Samsung", "mobile-phone", 19500,
        model="SM-A155F", was=21500, stock=30, warranty=12,
        highlights=["Big AMOLED screen for the money",
                    "5000mAh battery lasts two days of light use",
                    "Dedicated microSD slot"],
        specs={
            "General": [("Type", "Smartphone"), ("Operating System", "Android 14")],
            "Display": [("Size", "6.5 inch"), ("Resolution", "2340 x 1080"),
                        ("Panel Type", "Super AMOLED"), ("Refresh Rate", "90Hz")],
            "Performance": [("Processor", "MediaTek Helio G99"), ("RAM", "6GB"),
                            ("Storage", "128GB")],
            "Camera": [("Main Camera", "50MP"), ("Front Camera", "13MP")],
            "Battery": [("Capacity", "5000mAh"), ("Charging", "25W")],
        },
    ),
    P(
        "Apple iPhone 15", "Apple", "mobile-phone", 152000,
        model="MTP63", stock=5, warranty=12,
        highlights=["USB-C at last", "48MP main camera with 2x zoom",
                    "Dynamic Island"],
        specs={
            "General": [("Type", "Smartphone"), ("Operating System", "iOS 17")],
            "Display": [("Size", "6.1 inch"), ("Resolution", "2556 x 1179"),
                        ("Panel Type", "Super Retina XDR OLED")],
            "Performance": [("Processor", "Apple A16 Bionic"), ("Storage", "128GB")],
            "Camera": [("Main Camera", "48MP"), ("Ultra-wide", "12MP"),
                       ("Front Camera", "12MP")],
            "Battery": [("Rated Video Playback", "Up to 20 hours")],
        },
    ),

    # --------------------------------------------------------------- Tablet
    P(
        "Samsung Galaxy Tab A9+ 11\"", "Samsung", "tablet", 32500,
        model="SM-X210", was=35500, stock=11, warranty=12,
        highlights=["11-inch 90Hz screen", "Quad speakers tuned by AKG",
                    "Good for study notes and streaming"],
        specs={
            "General": [("Type", "Tablet"), ("Operating System", "Android 13")],
            "Display": [("Size", "11 inch"), ("Resolution", "1920 x 1200"),
                        ("Panel Type", "TFT"), ("Refresh Rate", "90Hz")],
            "Performance": [("Processor", "Snapdragon 695"), ("RAM", "8GB"),
                            ("Storage", "128GB")],
            "Battery": [("Capacity", "7040mAh"), ("Charging", "15W")],
        },
    ),
    P(
        "Apple iPad 10th Generation 10.9\"", "Apple", "tablet", 78000,
        model="MPQ03", stock=7, warranty=12,
        highlights=["Bright 10.9-inch Liquid Retina display",
                    "Landscape front camera for video calls",
                    "Works with Apple Pencil (1st gen)"],
        specs={
            "General": [("Type", "Tablet"), ("Operating System", "iPadOS 16")],
            "Display": [("Size", "10.9 inch"), ("Resolution", "2360 x 1640"),
                        ("Panel Type", "Liquid Retina IPS")],
            "Performance": [("Processor", "Apple A14 Bionic"), ("Storage", "64GB")],
            "Camera": [("Rear Camera", "12MP"), ("Front Camera", "12MP Ultra Wide")],
        },
    ),
    P(
        "Xiaomi Pad 6", "Xiaomi", "tablet", 42500,
        model="23043RP34G", was=46000, stock=8, warranty=12,
        highlights=["144Hz 2.8K display", "Snapdragon 870",
                    "33W fast charging"],
        specs={
            "General": [("Type", "Tablet"), ("Operating System", "Android 13")],
            "Display": [("Size", "11 inch"), ("Resolution", "2880 x 1800"),
                        ("Panel Type", "IPS"), ("Refresh Rate", "144Hz")],
            "Performance": [("Processor", "Snapdragon 870"), ("RAM", "8GB"),
                            ("Storage", "256GB")],
            "Battery": [("Capacity", "8840mAh"), ("Charging", "33W")],
        },
    ),

    # ------------------------------------------------------------ Keyboards
    P(
        "Logitech MX Keys S Wireless Keyboard", "Logitech", "keyboard", 13500,
        model="920-011565", was=15000, stock=17, warranty=12,
        highlights=["Backlighting that reacts to your hands",
                    "Pairs with three devices at once",
                    "Charges over USB-C"],
        specs={
            "General": [("Type", "Wireless Keyboard"), ("Layout", "Full size"),
                        ("Colour", "Graphite")],
            "Features": [("Switch Type", "Scissor"), ("Backlight", "Smart backlighting"),
                         ("Multi-device", "Up to 3 devices")],
            "Connectivity": [("Wireless", "Bluetooth / Logi Bolt receiver"),
                             ("Battery Life", "Up to 10 days with backlight")],
        },
        component={"slot": "keyboard", "power_watts": 0},
    ),
    P(
        "Razer BlackWidow V4 X Mechanical Keyboard", "Razer", "keyboard", 16500,
        model="RZ03-04700200", stock=9, warranty=24,
        highlights=["Razer Green clicky switches",
                    "Per-key RGB lighting", "Six dedicated macro keys"],
        specs={
            "General": [("Type", "Mechanical Keyboard"), ("Layout", "Full size")],
            "Features": [("Switch Type", "Razer Green (Clicky)"),
                         ("Backlight", "Per-key RGB"), ("Polling Rate", "1000Hz"),
                         ("N-Key Rollover", "Yes")],
            "Connectivity": [("Interface", "USB-A wired"), ("Cable Length", "1.8m")],
        },
        component={"slot": "keyboard", "power_watts": 0},
    ),
    P(
        "Havit KB487L Mechanical Gaming Keyboard", "Havit", "keyboard", 4200,
        model="KB487L", was=4900, stock=26, warranty=12,
        highlights=["Hot-swappable switches at an entry price",
                    "RGB backlight with preset patterns",
                    "Compact 87-key layout"],
        specs={
            "General": [("Type", "Mechanical Keyboard"), ("Layout", "TKL (87 keys)")],
            "Features": [("Switch Type", "Blue (Hot-swappable)"),
                         ("Backlight", "RGB")],
            "Connectivity": [("Interface", "USB-A wired")],
        },
        component={"slot": "keyboard", "power_watts": 0},
    ),
    P(
        "A4Tech KR-85 Comfort Round Keyboard", "A4Tech", "keyboard", 1150,
        model="KR-85", stock=48, warranty=12,
        highlights=["Quiet membrane keys", "Spill-resistant tray",
                    "Straightforward plug-and-play"],
        specs={
            "General": [("Type", "Membrane Keyboard"), ("Layout", "Full size")],
            "Connectivity": [("Interface", "USB-A wired")],
        },
        component={"slot": "keyboard", "power_watts": 0},
    ),

    # ----------------------------------------------------------------- Mice
    P(
        "Logitech MX Master 3S Wireless Mouse", "Logitech", "mouse", 13500,
        model="910-006563", was=15000, stock=19, warranty=12, featured=True,
        highlights=["Near-silent clicks", "8K DPI sensor tracks on glass",
                    "Electromagnetic scroll wheel"],
        specs={
            "General": [("Type", "Wireless Mouse"), ("Colour", "Graphite"),
                        ("Hand Orientation", "Right-handed")],
            "Performance": [("Sensor", "Darkfield"), ("Maximum DPI", "8000"),
                            ("Buttons", "7")],
            "Connectivity": [("Wireless", "Bluetooth / Logi Bolt"),
                             ("Battery Life", "Up to 70 days")],
        },
        component={"slot": "mouse", "power_watts": 0},
    ),
    P(
        "Razer DeathAdder V3 Gaming Mouse", "Razer", "mouse", 8500,
        model="RZ01-04640100", stock=12, warranty=24,
        highlights=["59g shape built for long sessions",
                    "30K DPI optical sensor", "Optical switches rated to 90M clicks"],
        specs={
            "General": [("Type", "Gaming Mouse"), ("Hand Orientation", "Right-handed"),
                        ("Weight", "59g")],
            "Performance": [("Sensor", "Focus Pro 30K Optical"),
                            ("Maximum DPI", "30000"), ("Polling Rate", "1000Hz"),
                            ("Buttons", "6")],
            "Connectivity": [("Interface", "USB-A wired")],
        },
        component={"slot": "mouse", "power_watts": 0},
    ),
    P(
        "Logitech G102 Lightsync Gaming Mouse", "Logitech", "mouse", 2450,
        model="910-005806", was=2900, stock=40, warranty=24,
        highlights=["The default first gaming mouse",
                    "Adjustable up to 8000 DPI", "Programmable RGB"],
        specs={
            "General": [("Type", "Gaming Mouse"), ("Weight", "85g")],
            "Performance": [("Maximum DPI", "8000"), ("Buttons", "6"),
                            ("Polling Rate", "1000Hz")],
            "Connectivity": [("Interface", "USB-A wired")],
        },
        component={"slot": "mouse", "power_watts": 0},
    ),
    P(
        "A4Tech OP-720 Optical Mouse", "A4Tech", "mouse", 550,
        model="OP-720", stock=75, warranty=12,
        highlights=["Cheap, reliable spare", "1000 DPI optical sensor",
                    "Works on almost any surface"],
        specs={
            "General": [("Type", "Optical Mouse")],
            "Performance": [("Maximum DPI", "1000"), ("Buttons", "3")],
            "Connectivity": [("Interface", "USB-A wired")],
        },
        component={"slot": "mouse", "power_watts": 0},
    ),

    # ----------------------------------------------------------- Headphones
    P(
        "Sony WH-1000XM5 Wireless Noise Cancelling Headphones", "Sony", "headphone",
        42500, model="WH1000XM5/B", was=46500, stock=8, warranty=12, featured=True,
        highlights=["Class-leading noise cancelling",
                    "30-hour battery life", "Speak-to-chat pauses automatically"],
        specs={
            "General": [("Type", "Over-ear Wireless Headphones"), ("Colour", "Black")],
            "Audio": [("Driver Size", "30mm"),
                      ("Frequency Response", "4Hz - 40,000Hz"),
                      ("Noise Cancelling", "Active, dual processor")],
            "Battery": [("Playback Time", "30 hours"),
                        ("Quick Charge", "3 hours from 3 minutes")],
            "Connectivity": [("Bluetooth", "5.2"), ("Codecs", "SBC, AAC, LDAC"),
                             ("Multipoint", "Yes")],
        },
    ),
    P(
        "Havit H2002d Wired Gaming Headset", "Havit", "headphone", 2350,
        model="H2002D", was=2800, stock=34, warranty=12,
        highlights=["53mm drivers", "Detachable boom microphone",
                    "In-line volume control"],
        specs={
            "General": [("Type", "Wired Gaming Headset")],
            "Audio": [("Driver Size", "53mm"), ("Impedance", "32 Ohm"),
                      ("Microphone", "Omnidirectional")],
            "Connectivity": [("Interface", "3.5mm + USB (lighting only)"),
                             ("Cable Length", "2.2m")],
        },
    ),
    P(
        "Samsung Galaxy Buds2 Pro", "Samsung", "headphone", 16500,
        model="SM-R510", stock=13, warranty=12,
        highlights=["Small enough to forget you are wearing them",
                    "Intelligent active noise cancelling", "24-bit Hi-Fi audio"],
        specs={
            "General": [("Type", "True Wireless Earbuds")],
            "Audio": [("Driver", "Two-way (woofer + tweeter)"),
                      ("Noise Cancelling", "Active")],
            "Battery": [("Playback Time", "5 hours (18 with case)")],
            "Connectivity": [("Bluetooth", "5.3")],
        },
    ),

    # -------------------------------------------------------------- Speaker
    P(
        "Logitech Z313 2.1 Speaker System", "Logitech", "speaker", 5900,
        model="980-000414", was=6800, stock=15, warranty=12,
        highlights=["25W of sound with a real subwoofer",
                    "Wired control pod within reach",
                    "Works with anything that has a 3.5mm output"],
        specs={
            "General": [("Type", "2.1 Speaker System")],
            "Audio": [("Total Power", "25W RMS"), ("Subwoofer Power", "15W"),
                      ("Frequency Response", "48Hz - 20kHz")],
            "Connectivity": [("Input", "3.5mm"), ("Headphone Out", "Yes")],
        },
    ),
    P(
        "Havit SF120 Bluetooth Soundbar", "Havit", "speaker", 3200,
        model="SF120BT", stock=22, warranty=12,
        highlights=["Sits neatly under a monitor",
                    "Bluetooth or 3.5mm", "USB powered"],
        specs={
            "General": [("Type", "Soundbar")],
            "Audio": [("Total Power", "10W RMS")],
            "Connectivity": [("Bluetooth", "5.0"), ("Input", "3.5mm, USB")],
        },
    ),

    # ----------------------------------------------------------- Microphone
    P(
        "Havit GK56 USB Condenser Microphone", "Havit", "microphone", 3900,
        model="GK56", was=4500, stock=18, warranty=12,
        highlights=["Plug-and-play over USB",
                    "Cardioid pattern rejects room noise",
                    "Desk stand and pop filter included"],
        specs={
            "General": [("Type", "USB Condenser Microphone")],
            "Audio": [("Polar Pattern", "Cardioid"), ("Sample Rate", "48kHz"),
                      ("Bit Depth", "16-bit")],
            "Connectivity": [("Interface", "USB-C")],
        },
    ),

    # --------------------------------------------------------------- Webcam
    P(
        "Logitech C920 HD Pro Webcam", "Logitech", "webcam", 9500,
        model="960-001055", was=10500, stock=16, warranty=24,
        highlights=["Sharp 1080p at 30fps",
                    "Two microphones for stereo pickup",
                    "Clips to a monitor or screws to a tripod"],
        specs={
            "General": [("Type", "Webcam")],
            "Video": [("Resolution", "1920 x 1080"), ("Frame Rate", "30fps"),
                      ("Field of View", "78 degrees"), ("Focus", "Autofocus")],
            "Audio": [("Microphone", "Dual stereo")],
            "Connectivity": [("Interface", "USB-A")],
        },
    ),

    # ------------------------------------------------------------ Networking
    P(
        "TP-Link Archer AX53 AX3000 Wi-Fi 6 Router", "TP-Link", "router", 7900,
        model="ARCHER AX53", was=8900, stock=21, warranty=36, featured=True,
        highlights=["Wi-Fi 6 speeds up to 3 Gbps",
                    "Four antennas for whole-flat coverage",
                    "Set up from a phone in minutes"],
        specs={
            "General": [("Type", "Wi-Fi Router"), ("Wi-Fi Standard", "Wi-Fi 6 (802.11ax)")],
            "Performance": [("Speed", "AX3000 (2402 + 574 Mbps)"),
                            ("Antennas", "4 external"), ("Processor", "Triple-core")],
            "Connectivity": [("WAN Port", "1 x Gigabit"), ("LAN Ports", "4 x Gigabit"),
                             ("USB", "None")],
            "Features": [("MU-MIMO", "Yes"), ("OFDMA", "Yes"), ("WPA3", "Yes")],
        },
    ),
    P(
        "TP-Link Deco M4 Mesh Wi-Fi System (3-Pack)", "TP-Link", "router", 15500,
        model="DECO M4 3P", stock=9, warranty=36,
        highlights=["Covers up to 5,500 sq ft on one network name",
                    "Units hand your phone over as you walk",
                    "Parental controls built in"],
        specs={
            "General": [("Type", "Mesh Wi-Fi System"),
                        ("Wi-Fi Standard", "Wi-Fi 5 (802.11ac)")],
            "Performance": [("Speed", "AC1200"), ("Coverage", "Up to 5,500 sq ft"),
                            ("Units", "3")],
            "Connectivity": [("Ports per Unit", "2 x Gigabit")],
        },
    ),
    P(
        "TP-Link TL-SG108 8-Port Gigabit Switch", "TP-Link", "network-switch", 2400,
        model="TL-SG108", stock=28, warranty=36,
        highlights=["Eight gigabit ports, no configuration needed",
                    "Metal case runs cool and fanless",
                    "Wall-mountable"],
        specs={
            "General": [("Type", "Unmanaged Switch"), ("Ports", "8 x Gigabit")],
            "Performance": [("Switching Capacity", "16 Gbps"),
                            ("MAC Address Table", "4K")],
            "Physical": [("Housing", "Steel"), ("Cooling", "Fanless")],
        },
    ),
    P(
        "TP-Link Archer T3U AC1300 USB Wi-Fi Adapter", "TP-Link", "network-adapter",
        1950, model="ARCHER T3U", was=2300, stock=32, warranty=24,
        highlights=["Adds dual-band Wi-Fi to any desktop",
                    "Small enough to leave plugged in",
                    "USB 3.0 for full speed"],
        specs={
            "General": [("Type", "USB Wi-Fi Adapter"),
                        ("Wi-Fi Standard", "Wi-Fi 5 (802.11ac)")],
            "Performance": [("Speed", "AC1300 (867 + 400 Mbps)"), ("Bands", "Dual band")],
            "Connectivity": [("Interface", "USB 3.0")],
        },
    ),

    # ------------------------------------------------------------------ UPS
    P(
        "MicroMart Guard 1200VA Line-Interactive UPS", "Walton", "ups", 9500,
        model="TT-GUARD-1200", was=10800, stock=17, warranty=24,
        highlights=["Keeps a desktop alive through a load-shedding cut",
                    "Automatic voltage regulation",
                    "Audible alarm when the battery runs low"],
        specs={
            "General": [("Type", "Line-Interactive UPS"), ("Capacity", "1200VA / 720W")],
            "Power": [("Input Voltage", "165-275V AC"), ("Output Voltage", "220V AC"),
                      ("Backup Time", "20-30 minutes typical"),
                      ("Transfer Time", "Under 6ms")],
            "Battery": [("Battery Type", "Sealed lead-acid"), ("Recharge Time", "6-8 hours")],
            "Outlets": [("Sockets", "4 universal")],
        },
    ),
    P(
        "MicroMart Guard 650VA Offline UPS", "Walton", "ups", 5200,
        model="TT-GUARD-650", stock=24, warranty=24,
        highlights=["Enough to save your work and shut down safely",
                    "Compact enough for a desk shelf",
                    "Two universal sockets"],
        specs={
            "General": [("Type", "Offline UPS"), ("Capacity", "650VA / 360W")],
            "Power": [("Backup Time", "10-15 minutes typical"),
                      ("Transfer Time", "Under 10ms")],
            "Outlets": [("Sockets", "2 universal")],
        },
    ),

    # --------------------------------------------------------------- Camera
    P(
        "Sony Alpha ZV-E10 Mirrorless Camera (16-50mm Kit)", "Sony",
        "mirrorless-camera", 92000, model="ZV-E10L", was=99000, stock=4, warranty=12,
        highlights=["Built for video with a flip-out screen",
                    "APS-C sensor with interchangeable lenses",
                    "Background defocus at the press of a button"],
        specs={
            "General": [("Type", "Mirrorless Camera"), ("Mount", "Sony E")],
            "Sensor": [("Sensor Type", "APS-C CMOS"), ("Resolution", "24.2MP"),
                       ("ISO Range", "100-32000")],
            "Video": [("Maximum Resolution", "4K 30fps"), ("Slow Motion", "1080p 120fps")],
            "Display": [("Screen", "3.0 inch vari-angle touchscreen")],
            "Kit": [("Included Lens", "E PZ 16-50mm f/3.5-5.6 OSS")],
        },
    ),
    P(
        "Canon EOS R50 Mirrorless Camera (18-45mm Kit)", "Canon",
        "mirrorless-camera", 88000, model="EOS R50 KIT", stock=5, warranty=12,
        highlights=["Light enough to carry every day",
                    "Reliable subject-tracking autofocus",
                    "Uncropped 4K video"],
        specs={
            "General": [("Type", "Mirrorless Camera"), ("Mount", "Canon RF")],
            "Sensor": [("Sensor Type", "APS-C CMOS"), ("Resolution", "24.2MP")],
            "Video": [("Maximum Resolution", "4K 30fps (uncropped)")],
            "Display": [("Screen", "3.0 inch vari-angle touchscreen"),
                        ("Viewfinder", "2.36M-dot EVF")],
        },
    ),
    P(
        "MicroMart ActionCam 4K Waterproof Camera", "Havit", "action-camera", 8900,
        model="TT-ACT4K", was=10500, stock=13, warranty=12,
        highlights=["4K recording in a body you can drop",
                    "Waterproof case to 30m included",
                    "Bundled mounts for a helmet or handlebar"],
        specs={
            "General": [("Type", "Action Camera")],
            "Video": [("Maximum Resolution", "4K 30fps"),
                      ("Stabilisation", "Electronic (EIS)")],
            "Sensor": [("Resolution", "20MP"), ("Field of View", "170 degrees")],
            "Durability": [("Waterproof", "30m with case")],
            "Battery": [("Capacity", "1050mAh"), ("Included Batteries", "2")],
        },
    ),

    # -------------------------------------------------------------- Printer
    P(
        "Epson EcoTank L3250 All-in-One Ink Tank Printer", "Epson",
        "inkjet-printer", 24500, model="L3250", was=26500, stock=12, warranty=12,
        highlights=["Refillable tanks instead of cartridges",
                    "Prints, scans and copies",
                    "Wi-Fi printing from a phone"],
        specs={
            "General": [("Type", "All-in-One Ink Tank Printer"),
                        ("Functions", "Print, Scan, Copy")],
            "Print": [("Print Speed (Black)", "33 ppm"), ("Print Speed (Colour)", "15 ppm"),
                      ("Resolution", "5760 x 1440 dpi"), ("Duplex", "Manual")],
            "Scan": [("Scanner Type", "Flatbed CIS"), ("Scan Resolution", "1200 x 2400 dpi")],
            "Connectivity": [("Wireless", "Wi-Fi, Wi-Fi Direct"), ("USB", "USB 2.0")],
        },
    ),
    P(
        "HP LaserJet Pro M141w Multifunction Printer", "HP", "laser-printer",
        22500, model="7MD74A", stock=10, warranty=12,
        highlights=["Sharp text at 20 pages a minute",
                    "Wireless setup from the HP Smart app",
                    "Compact enough for a home desk"],
        specs={
            "General": [("Type", "Monochrome Laser MFP"),
                        ("Functions", "Print, Scan, Copy")],
            "Print": [("Print Speed", "20 ppm"), ("Resolution", "600 x 600 dpi"),
                      ("Monthly Duty Cycle", "8,000 pages")],
            "Connectivity": [("Wireless", "Wi-Fi"), ("USB", "USB 2.0")],
        },
    ),
    P(
        "Brother DCP-T520W Ink Tank Printer", "Brother", "inkjet-printer", 21500,
        model="DCP-T520W", was=23500, stock=14, warranty=24,
        highlights=["High-yield refillable tanks",
                    "Two-year warranty", "Wireless and mobile printing"],
        specs={
            "General": [("Type", "All-in-One Ink Tank Printer"),
                        ("Functions", "Print, Scan, Copy")],
            "Print": [("Print Speed (Black)", "17 ipm"), ("Print Speed (Colour)", "9.5 ipm")],
            "Connectivity": [("Wireless", "Wi-Fi"), ("USB", "USB 2.0")],
        },
    ),

    # ------------------------------------------------------------ Projector
    P(
        "Epson EB-S41 SVGA 3LCD Projector", "Epson", "projector", 52000,
        model="EB-S41", stock=6, warranty=24,
        highlights=["3,300 lumens, bright enough for a lit classroom",
                    "3LCD keeps colour as bright as white",
                    "Lamp rated for 12,000 hours in eco mode"],
        specs={
            "General": [("Type", "3LCD Projector")],
            "Projection": [("Brightness", "3300 lumens"), ("Native Resolution", "800 x 600"),
                           ("Contrast Ratio", "15000:1"), ("Lamp Life", "12,000 hours (eco)")],
            "Connectivity": [("HDMI", "1"), ("VGA", "1"), ("USB", "1")],
        },
    ),
    P(
        "MicroMart CinemaLite 1080p LED Projector", "Havit", "projector", 28500,
        model="TT-CINE-1080", was=32000, stock=8, warranty=12,
        highlights=["Native 1080p for film nights",
                    "Screen mirroring from a phone",
                    "Built-in speakers"],
        specs={
            "General": [("Type", "LED Projector")],
            "Projection": [("Brightness", "4500 lumens"), ("Native Resolution", "1920 x 1080"),
                           ("Screen Size", "40 to 200 inches")],
            "Connectivity": [("HDMI", "2"), ("USB", "2"), ("Wireless", "Wi-Fi mirroring")],
        },
    ),

    # ------------------------------------------------------------------- TV
    P(
        "Samsung 43\" Crystal UHD 4K Smart TV", "Samsung", "tv", 52000,
        model="UA43CU7000", was=57000, stock=7, warranty=24,
        highlights=["4K with Samsung's Crystal processor",
                    "Tizen apps built in", "Slim enough to wall-mount flush"],
        specs={
            "General": [("Type", "Smart LED TV"), ("Screen Size", "43 inch")],
            "Display": [("Resolution", "3840 x 2160"), ("Refresh Rate", "60Hz"),
                        ("HDR", "HDR10+")],
            "Smart": [("Operating System", "Tizen"), ("Voice Assistant", "Bixby")],
            "Connectivity": [("HDMI", "3"), ("USB", "1"), ("Wireless", "Wi-Fi, Bluetooth")],
        },
    ),
    P(
        "LG 55\" UHD 4K Smart TV", "LG", "tv", 78500,
        model="55UR7500PSC", stock=5, warranty=24,
        highlights=["55-inch 4K panel", "webOS with the major streaming apps",
                    "Slim bezels on three sides"],
        specs={
            "General": [("Type", "Smart LED TV"), ("Screen Size", "55 inch")],
            "Display": [("Resolution", "3840 x 2160"), ("Refresh Rate", "60Hz"),
                        ("HDR", "HDR10 Pro")],
            "Smart": [("Operating System", "webOS"), ("Voice Assistant", "ThinQ AI")],
            "Connectivity": [("HDMI", "3"), ("USB", "2")],
        },
    ),
    P(
        "Walton 32\" HD Smart LED TV", "Walton", "tv", 24500,
        model="W32D210G", was=27500, stock=16, warranty=36,
        highlights=["Sensible size for a bedroom",
                    "Three-year panel warranty", "Local service network"],
        specs={
            "General": [("Type", "Smart LED TV"), ("Screen Size", "32 inch")],
            "Display": [("Resolution", "1366 x 768"), ("Refresh Rate", "60Hz")],
            "Smart": [("Operating System", "Android TV")],
            "Connectivity": [("HDMI", "2"), ("USB", "2")],
        },
    ),

    # ------------------------------------------------------- Air conditioner
    P(
        "Walton 1.5 Ton Inverter Split Air Conditioner", "Walton",
        "air-conditioner", 62500, model="WSI-KRYSTALINE-18F", was=68000,
        stock=9, warranty=60,
        highlights=["Inverter compressor cuts the running cost",
                    "Cools a 180 sq ft room quickly",
                    "Five-year compressor warranty"],
        specs={
            "General": [("Type", "Split Air Conditioner"), ("Capacity", "1.5 Ton (18000 BTU)")],
            "Performance": [("Cooling Capacity", "18000 BTU/hr"), ("Energy Rating", "5 star"),
                            ("Compressor", "Inverter rotary"),
                            ("Suitable Room Size", "Up to 180 sq ft")],
            "Features": [("Modes", "Cool, Dry, Fan, Turbo"), ("Filter", "Anti-dust"),
                         ("Remote", "Included")],
        },
    ),
    P(
        "Walton 1 Ton Non-Inverter Split AC", "Walton", "air-conditioner", 44500,
        model="WSN-RIVERINE-12C", stock=11, warranty=60,
        highlights=["Straightforward cooling for a small room",
                    "Copper condenser", "Five-year compressor warranty"],
        specs={
            "General": [("Type", "Split Air Conditioner"), ("Capacity", "1 Ton (12000 BTU)")],
            "Performance": [("Cooling Capacity", "12000 BTU/hr"),
                            ("Compressor", "Rotary"),
                            ("Suitable Room Size", "Up to 120 sq ft")],
        },
    ),

    # --------------------------------------------------------------- Gadget
    P(
        "Samsung Galaxy Watch6 44mm Bluetooth", "Samsung", "smart-watch", 32500,
        model="SM-R940", was=35500, stock=10, warranty=12,
        highlights=["Sleep tracking that is actually readable",
                    "Body composition measurement",
                    "Sapphire crystal glass"],
        specs={
            "General": [("Type", "Smart Watch"), ("Case Size", "44mm")],
            "Display": [("Size", "1.5 inch"), ("Resolution", "480 x 480"),
                        ("Panel Type", "Super AMOLED")],
            "Health": [("Sensors", "Heart rate, ECG, BIA, temperature"),
                       ("Sleep Tracking", "Yes")],
            "Battery": [("Capacity", "425mAh"), ("Rated Life", "Up to 40 hours")],
            "Durability": [("Water Resistance", "5ATM + IP68")],
        },
    ),
    P(
        "Xiaomi Smart Band 8", "Xiaomi", "smart-watch", 4900,
        model="M2239B1", was=5600, stock=35, warranty=12,
        highlights=["Two weeks between charges",
                    "AMOLED screen you can read outdoors",
                    "Over 150 workout modes"],
        specs={
            "General": [("Type", "Fitness Band")],
            "Display": [("Size", "1.62 inch"), ("Panel Type", "AMOLED"),
                        ("Brightness", "600 nits")],
            "Health": [("Sensors", "Heart rate, SpO2, sleep")],
            "Battery": [("Rated Life", "Up to 16 days")],
            "Durability": [("Water Resistance", "5ATM")],
        },
    ),
    P(
        "Anker PowerCore 20000mAh Power Bank", "Anker", "power-bank", 5500,
        model="A1287", was=6200, stock=27, warranty=18,
        highlights=["Charges a phone four to five times",
                    "20W USB-C output for fast charging",
                    "Trickle mode for earbuds and watches"],
        specs={
            "General": [("Type", "Power Bank"), ("Capacity", "20000mAh")],
            "Power": [("USB-C Output", "20W PD"), ("USB-A Output", "18W"),
                      ("Input", "USB-C 20W")],
            "Physical": [("Weight", "343g")],
        },
    ),
    P(
        "Anker 65W GaN USB-C Charger", "Anker", "power-bank", 4200,
        model="A2663", stock=23, warranty=18,
        highlights=["Charges a laptop and a phone at once",
                    "GaN keeps it pocket-sized",
                    "Foldable plug"],
        specs={
            "General": [("Type", "Wall Charger"), ("Total Output", "65W")],
            "Power": [("Ports", "2 x USB-C, 1 x USB-A"),
                      ("Protocols", "Power Delivery 3.0, PPS")],
        },
    ),

    # --------------------------------------------------------------- Gaming
    P(
        "MicroMart Apex Ergonomic Gaming Chair", "Havit", "gaming-chair", 18500,
        model="TT-APEX-CHAIR", was=21500, stock=8, warranty=12,
        highlights=["Reclines to 155 degrees",
                    "Adjustable lumbar cushion and headrest",
                    "4D armrests"],
        specs={
            "General": [("Type", "Gaming Chair"), ("Upholstery", "PU leather")],
            "Adjustment": [("Recline", "90-155 degrees"), ("Armrests", "4D adjustable"),
                           ("Height Adjust", "Gas lift class 4")],
            "Capacity": [("Maximum Load", "120 kg"),
                         ("Recommended Height", "160-190cm")],
        },
    ),
    P(
        "Sony PlayStation 5 Slim Digital Edition", "Sony", "gaming-console", 68500,
        model="CFI-2016B", stock=4, warranty=12, featured=True,
        highlights=["Loads games in seconds from the custom SSD",
                    "DualSense controller with haptic feedback",
                    "Digital library, no disc drive"],
        specs={
            "General": [("Type", "Games Console"), ("Edition", "Digital")],
            "Performance": [("Processor", "AMD Zen 2 8-core"),
                            ("Graphics", "AMD RDNA 2, 10.28 TFLOPS"),
                            ("Storage", "1TB NVMe SSD"), ("Memory", "16GB GDDR6")],
            "Video": [("Maximum Output", "4K 120Hz / 8K"), ("Ray Tracing", "Yes")],
        },
    ),
    P(
        "Xbox Wireless Controller", "Microsoft", "controller", 9500,
        model="QAT-00002", was=10500, stock=15, warranty=12,
        highlights=["Works with Xbox, Windows and Android",
                    "Textured grips on the triggers",
                    "Dedicated share button"],
        specs={
            "General": [("Type", "Wireless Controller"), ("Colour", "Carbon Black")],
            "Connectivity": [("Wireless", "Bluetooth / Xbox Wireless"),
                             ("Wired", "USB-C")],
            "Power": [("Battery", "2 x AA"), ("Rated Life", "Up to 40 hours")],
        },
    ),

    # ------------------------------------------------------------- Software
    P(
        "Microsoft Office Home & Student 2021", "Microsoft", "software", 14500,
        model="79G-05387", stock=25, warranty=0,
        highlights=["Word, Excel and PowerPoint",
                    "One-time purchase, no subscription",
                    "Licensed for one PC or Mac"],
        specs={
            "General": [("Type", "Productivity Software"), ("Licence", "One-time, 1 device"),
                        ("Delivery", "Product key card")],
            "Includes": [("Applications", "Word, Excel, PowerPoint"),
                         ("Platform", "Windows 11/10 or macOS")],
        },
    ),
    P(
        "Microsoft Windows 11 Home OEM Licence", "Microsoft", "software", 12500,
        model="KW9-00664", was=13800, stock=30, warranty=0,
        highlights=["Genuine OEM licence",
                    "Tied to the machine it is first activated on",
                    "Includes all feature updates"],
        specs={
            "General": [("Type", "Operating System"), ("Licence", "OEM, 1 device"),
                        ("Delivery", "Sealed key card")],
            "Requirements": [("Processor", "1GHz 64-bit, 2 cores"), ("RAM", "4GB"),
                             ("Storage", "64GB"), ("Firmware", "UEFI with Secure Boot, TPM 2.0")],
        },
    ),

    # ------------------------------------------------------ Server & storage
    P(
        "Synology DS223j 2-Bay NAS Enclosure", "Synology", "nas-storage", 42500,
        model="DS223J", stock=5, warranty=24,
        highlights=["Your own backup and media server",
                    "Two drive bays with mirroring",
                    "Drives sold separately"],
        specs={
            "General": [("Type", "Network Attached Storage"), ("Bays", "2"),
                        ("Drives Included", "None")],
            "Performance": [("Processor", "Realtek RTD1619B quad-core"), ("RAM", "1GB DDR4")],
            "Connectivity": [("LAN", "1 x Gigabit"), ("USB", "2 x USB 3.2 Gen 1")],
            "Storage": [("Maximum Capacity", "2 x 22TB"),
                        ("RAID Support", "RAID 0, RAID 1, JBOD, Basic")],
        },
    ),
    P(
        "Western Digital My Passport 2TB Portable Drive", "Western Digital",
        "external-storage", 8500, model="WDBYVG0020BBK", was=9500, stock=24,
        warranty=36,
        highlights=["2TB that fits in a shirt pocket",
                    "Password protection with hardware encryption",
                    "USB 3.0, no power adapter needed"],
        specs={
            "General": [("Type", "Portable Hard Drive"), ("Capacity", "2TB"),
                        ("Colour", "Black")],
            "Performance": [("Interface", "USB 3.2 Gen 1"), ("Transfer Speed", "Up to 5 Gbps")],
            "Security": [("Encryption", "256-bit AES hardware")],
        },
    ),
    P(
        "Samsung T7 1TB Portable SSD", "Samsung", "external-storage", 12500,
        model="MU-PC1T0T", stock=15, warranty=36,
        highlights=["1,050 MB/s over USB-C",
                    "Shock-resistant with no moving parts",
                    "Credit-card footprint"],
        specs={
            "General": [("Type", "Portable SSD"), ("Capacity", "1TB")],
            "Performance": [("Interface", "USB 3.2 Gen 2"),
                            ("Sequential Read", "1050 MB/s"),
                            ("Sequential Write", "1000 MB/s")],
            "Physical": [("Weight", "58g"), ("Shock Resistance", "Up to 2m drop")],
        },
    ),
    P(
        "Seagate Expansion 4TB Desktop External Drive", "Seagate",
        "external-storage", 13500, model="STKP4000400", was=14900, stock=12,
        warranty=24,
        highlights=["4TB for backups and media archives",
                    "Plug in and it appears, no software needed",
                    "Mains powered"],
        specs={
            "General": [("Type", "Desktop External Drive"), ("Capacity", "4TB")],
            "Performance": [("Interface", "USB 3.0")],
            "Power": [("Power Source", "External adapter")],
        },
    ),
]
