# Generated by Django 5.2.6 on 2026-08-19 07:08

import apps.common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ship_recipient_name', models.CharField(max_length=150)),
                ('ship_phone', models.CharField(max_length=20)),
                ('ship_division', models.CharField(max_length=64)),
                ('ship_district', models.CharField(max_length=64)),
                ('ship_upazila', models.CharField(blank=True, max_length=64)),
                ('ship_area', models.CharField(blank=True, max_length=128)),
                ('ship_street', models.CharField(max_length=255)),
                ('ship_postcode', models.CharField(blank=True, max_length=12)),
                ('subtotal', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_total', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_total', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_total', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate_applied', models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted percentage. A later rate change must not alter this order.', max_digits=5)),
                ('grand_total', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online (SSLCommerz)')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(help_text='Client-generated. Stops a double-submit becoming two orders.', max_length=64, unique=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(max_length=64)),
                ('unit_price', apps.common.fields.MoneyField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', apps.common.fields.MoneyField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'orders_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=16)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=16)),
                ('actor_role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin or staff'), ('system', 'System')], default='system', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'orders_order_status_log',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_name', models.CharField(max_length=120)),
                ('tracking_number', models.CharField(max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_shipment',
            },
        ),
    ]
