"""
Online payment logic.

A browser redirect is user-controllable, so it is never proof of payment. Only
handle_ipn can move an order forward, and the only thing it believes is the
response to its own outbound call to SSLCommerz's validation API:

* the browser callback reads nothing and writes nothing;
* the notification body is kept as evidence and nothing more. Even the order
  reference is taken from the validation response, so a forged body cannot
  aim a genuine payment at somebody else's order.

Confirmation goes through orders.services.placement.confirm_order, the same
path Cash on Delivery uses, so stock movement and the audit log are identical
however an order is paid.

Idempotency is a row lock plus a re-read: the order is locked before its
status is read, so two notifications arriving together serialise. A failed or
abandoned payment changes nothing -- the order stays pending and the customer
can retry.
"""
import logging
import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation

from django.conf import settings
from django.db import transaction
from django.urls import reverse
from django.utils import timezone

from apps.orders.models import Actor, Order, OrderStatus, PaymentMethod
from apps.orders.services import placement as placement_services
from config.exceptions import DomainError

from ..models import Payment, PaymentStatus
from . import sslcommerz

logger = logging.getLogger(__name__)

GATEWAY = "sslcommerz"
CURRENCY = "BDT"

CALLBACK_RESULTS = ("success", "fail", "cancel")

# A reference is ours, it is generated by placement.next_reference, and it ends
# up inside a URL we hand back to a browser. Anything that does not look like
# one is dropped rather than echoed.
REFERENCE_PATTERN = re.compile(r"^[A-Za-z0-9\-]{1,24}$")

# Outcomes of an IPN. Stable strings -- they are logged, and the admin surface
# in week 5 will want to filter on them.
REASON_CONFIRMED = "CONFIRMED"
REASON_ALREADY_CONFIRMED = "ALREADY_CONFIRMED"
REASON_ORDER_NOT_PAYABLE = "ORDER_NOT_PAYABLE"
REASON_NOT_AN_ONLINE_ORDER = "NOT_AN_ONLINE_ORDER"
REASON_VALIDATION_FAILED = "VALIDATION_FAILED"
REASON_CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
REASON_AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
REASON_CONFIRMATION_FAILED = "CONFIRMATION_FAILED"


@dataclass(frozen=True)
class PaymentSession:
    """What initiate hands back: where to send the browser, and what we stored."""

    order: object
    payment: object
    redirect_url: str
    session_key: str = ""


@dataclass(frozen=True)
class IPNResult:
    """
    One notification's verdict.

    `confirmed` is the only field that means anything financially; `reason`
    exists so a rejected notification can be told apart from an ignored replay
    in a log, which is the difference between an attack and a normal Tuesday.
    """

    confirmed: bool
    reason: str
    order: object = None
    payment: object = None
    validation: dict = None


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------
def _money(value):
    """
    A gateway figure as Decimal, or None if it is not a number at all.

    Deliberately never float. `float("1000.00") == float(order.grand_total)`
    happens to work today and stops working the first time a total ends in
    something binary floating point cannot hold -- and the failure mode is
    accepting an underpayment.
    """
    if value is None:
        return None
    try:
        return Decimal(str(value).strip())
    except (InvalidOperation, ValueError, TypeError):
        return None


def _jsonable(payload):
    """
    Flatten a gateway payload into something JSONField will accept.

    An IPN arrives as a form-encoded QueryDict; a validation response is
    already plain JSON. Both are stored verbatim in spirit -- keys are kept as
    they arrived and only unserialisable values are stringified.
    """
    if payload is None:
        return {}
    if hasattr(payload, "dict"):  # QueryDict
        payload = payload.dict()
    clean = {}
    for key, value in dict(payload).items():
        if isinstance(value, (str, int, float, bool)) or value is None:
            clean[str(key)] = value
        elif isinstance(value, Decimal):
            clean[str(key)] = str(value)
        elif isinstance(value, (list, tuple)):
            clean[str(key)] = [str(item) for item in value]
        else:
            clean[str(key)] = str(value)
    return clean


def _evidence(*, notification, validation):
    """
    Both sides of the story, kept apart (FR-PAY-6).

    `validation` is what we believe. `notification` is what we were *told*, and
    it is retained only because a dispute is easier to settle with the forged
    version in hand than without it. Nothing downstream may read from the
    notification half.
    """
    return {
        "gateway": GATEWAY,
        "recorded_at": timezone.now().isoformat(),
        "notification": _jsonable(notification),
        "validation": _jsonable(validation),
    }


def callback_urls(base_url=None):
    """
    The four URLs handed to the gateway.

    `base_url` is the *public origin of this API*, which the view derives from
    the request. Three of these are browser redirects and could point anywhere;
    `ipn` is the one that matters, and SSLCommerz must be able to reach it from
    the public internet -- which a laptop on localhost is not.
    """
    base = str(base_url or settings.FRONTEND_BASE_URL).rstrip("/")
    urls = {
        result: base + reverse("payments:callback", kwargs={"result": result})
        for result in CALLBACK_RESULTS
    }
    urls["ipn"] = base + reverse("payments:ipn")
    return urls


# ---------------------------------------------------------------------------
# Initiate (FR-PAY-2)
# ---------------------------------------------------------------------------
def _resolve_order(reference, *, user=None):
    """
    The order this reference names, or a 404-shaped refusal.

    Object-level authorisation, PRD 10.2: a registered customer's order belongs
    to that customer and nobody else, and a miss is 404 rather than 403 so the
    reference space is not confirmed. A guest order has no owner to check
    against -- the reference is the only capability a guest was ever issued,
    and it is the same capability the confirmation page uses.
    """
    reference = str(reference or "").strip()
    order = Order.objects.filter(reference=reference).first()
    if order is None:
        raise DomainError(
            "Not found.", code="NOT_FOUND", field="order_reference", status_code=404
        )

    if order.user_id is not None:
        requester = (
            user.pk
            if (user is not None and getattr(user, "is_authenticated", False))
            else None
        )
        if requester != order.user_id:
            raise DomainError(
                "Not found.",
                code="NOT_FOUND",
                field="order_reference",
                status_code=404,
            )
    return order


def assert_payable(order):
    """
    Refuse to open a checkout session for an order that must not be paid for.

    Order matters. "Already paid" is checked first because a paid order is also
    a confirmed one, and telling a customer their order "can no longer be paid
    for" when the truth is that it is already settled would be actively
    misleading.
    """
    payment = getattr(order, "payment", None)
    if payment is not None and payment.status == PaymentStatus.PAID:
        raise DomainError(
            "This order has already been paid.",
            code="ORDER_ALREADY_PAID",
            field="order_reference",
        )

    if order.payment_method != PaymentMethod.ONLINE:
        raise DomainError(
            "This order was not placed for online payment.",
            code="PAYMENT_METHOD_NOT_ONLINE",
            field="order_reference",
        )

    if order.status != OrderStatus.PENDING:
        raise DomainError(
            "This order can no longer be paid for.",
            code="ORDER_NOT_PAYABLE",
            field="order_reference",
        )

    if Decimal(order.grand_total) <= 0:
        raise DomainError(
            "There is nothing to pay on this order.",
            code="ORDER_NOT_PAYABLE",
            field="order_reference",
        )
    return order


def _session_payload(order, *, base_url, customer_ip=""):
    """
    The order-shaped half of the session request. Credentials are added by the
    client; nothing secret is assembled here.

    `total_amount` is `order.grand_total` and nothing else. The amount the
    gateway is asked for is the amount the server computed at placement, so the
    figure compared at validation time is a figure this application chose.
    """
    items = list(order.items.all())
    names = ", ".join(item.product_name for item in items[:5]) or order.reference
    urls = callback_urls(base_url)

    payload = {
        "total_amount": str(Decimal(order.grand_total)),
        "currency": CURRENCY,
        "tran_id": order.reference,
        "success_url": urls["success"],
        "fail_url": urls["fail"],
        "cancel_url": urls["cancel"],
        "ipn_url": urls["ipn"],
        "emi_option": 0,
        # Customer block -- SSLCommerz rejects a session with any of these blank.
        "cus_name": order.ship_recipient_name,
        "cus_email": order.email,
        "cus_phone": order.phone or order.ship_phone,
        "cus_add1": order.ship_street,
        "cus_city": order.ship_district,
        "cus_state": order.ship_division,
        "cus_postcode": order.ship_postcode or "0000",
        "cus_country": "Bangladesh",
        # Shipment block.
        "shipping_method": "Courier",
        "num_of_item": len(items),
        "ship_name": order.ship_recipient_name,
        "ship_add1": order.ship_street,
        "ship_city": order.ship_district,
        "ship_state": order.ship_division,
        "ship_postcode": order.ship_postcode or "0000",
        "ship_country": "Bangladesh",
        # Product block.
        "product_name": names[:255],
        "product_category": "Electronics",
        "product_profile": "physical-goods",
        # Echoed back on the callback and the IPN. Read as a convenience only,
        # never as identification -- value_a is as forgeable as anything else.
        "value_a": order.reference,
    }
    if customer_ip:
        payload["cus_ip"] = customer_ip
    return payload


def initiate_payment(*, order_reference, user=None, base_url=None, customer_ip=""):
    """
    POST /payments/initiate/ -- open a hosted-checkout session (FR-PAY-2).

    Returns a `PaymentSession`. Creating one moves no money and confirms
    nothing: the row it writes is INITIATED, which means "a customer was sent
    to the gateway", not "a customer paid".

    The gateway call happens *outside* the transaction on purpose. Holding a
    row lock across a network round trip to a third party is how one slow
    upstream turns into a pile of blocked connections. The order is re-locked
    and re-checked afterwards, so the window buys nothing for an attacker: an
    IPN that confirms the order mid-flight makes the write below refuse.
    """
    order = _resolve_order(order_reference, user=user)
    assert_payable(order)

    session = sslcommerz.create_session(
        _session_payload(order, base_url=base_url, customer_ip=customer_ip)
    )
    session_key = str(session.get("sessionkey") or "")[:128]

    with transaction.atomic():
        order = Order.objects.select_for_update().get(pk=order.pk)
        assert_payable(order)

        payment, _created = Payment.objects.update_or_create(
            order=order,
            defaults={
                "method": GATEWAY,
                "session_key": session_key,
                "amount": Decimal(order.grand_total),
                "currency": CURRENCY,
                "status": PaymentStatus.INITIATED,
                # A retry after a failed attempt starts a clean evidence
                # record; the old attempt's gateway ids would be misleading
                # attached to a new session.
                "gateway_txn_id": "",
                "confirmed_at": None,
                "raw_response": _evidence(notification=None, validation=session),
            },
        )

    return PaymentSession(
        order=order,
        payment=payment,
        redirect_url=session["GatewayPageURL"],
        session_key=session_key,
    )


# ---------------------------------------------------------------------------
# IPN (FR-PAY-4, FR-PAY-5) -- the only path that may confirm an order
# ---------------------------------------------------------------------------
def handle_ipn(notification):
    """
    POST /payments/ipn/ -- the gateway's server-to-server notification.

    Nothing in `notification` is trusted. Exactly one field is read from it --
    `val_id` -- and it is read as a *lookup key*, not as an assertion. What
    happens next is decided entirely by SSLCommerz's answer to our own outbound
    validation request, including which order this is about.

    A notification claiming `status=VALID` for a 200,000 taka order is
    therefore worth nothing on its own: the validation call either agrees or
    the order stays pending.
    """
    notification = dict(notification or {})

    val_id = str(notification.get("val_id") or "").strip()
    if not val_id:
        raise DomainError(
            "A payment notification without a val_id cannot be validated.",
            code="MISSING_VAL_ID",
            field="val_id",
            status_code=400,
        )

    validation = sslcommerz.validate_transaction(val_id)

    # The order reference comes off the validation response. Taking it from the
    # notification instead would let a forged body point a real, validated
    # payment for 500 taka at a 200,000 taka order.
    reference = str(validation.get("tran_id") or "").strip()
    if not reference:
        logger.warning(
            "sslcommerz validation for val_id=%s carried no tran_id", val_id
        )
        raise DomainError("Not found.", code="NOT_FOUND", status_code=404)

    with transaction.atomic():
        # FR-PAY-5. The lock is taken *before* the status is read, so two IPNs
        # for one order cannot both find it pending. The loser of the race
        # blocks here and re-reads a confirmed order on the other side.
        order = Order.objects.select_for_update().filter(reference=reference).first()
        if order is None:
            logger.warning(
                "sslcommerz validated tran_id=%s, which matches no order", reference
            )
            raise DomainError("Not found.", code="NOT_FOUND", status_code=404)

        return _apply_validated_ipn(
            order=order, notification=notification, validation=validation, val_id=val_id
        )


def _locked_payment(order):
    """
    The order's payment row, locked, or None if it has none.

    Locked in the same order as everything else in this module -- order first,
    then payment -- so no cycle can form with a concurrent initiate.
    """
    return Payment.objects.select_for_update().filter(order=order).first()


def _open_payment(order):
    """
    A payment row to record this notification against, created if the initiate
    write was lost -- a crash, a rolled-back deploy. The money still arrived,
    so the evidence gets somewhere to live.

    Called only once the notification is known to be about a payable online
    order: a Cash on Delivery order must not sprout a Payment row because
    somebody posted at the IPN endpoint.
    """
    return Payment.objects.create(
        order=order,
        method=GATEWAY,
        amount=Decimal(order.grand_total),
        currency=CURRENCY,
        status=PaymentStatus.PENDING,
    )


def _reject(payment, *, notification, validation):
    """
    Record a notification that did not confirm anything, and change nothing
    else (FR-PAY-7).

    The order is not touched, so it stays pending; stock is not touched,
    because only confirm_order moves stock; the cart is not touched, because
    nothing here knows what a cart is. The customer can try again -- a fresh
    initiate resets this row to INITIATED.
    """
    payment.status = PaymentStatus.FAILED
    payment.raw_response = _evidence(notification=notification, validation=validation)
    payment.save(update_fields=["status", "raw_response"])
    return payment


def _apply_validated_ipn(*, order, notification, validation, val_id):
    """
    Decide, inside the order's row lock, what a validated notification means.

    Every early return leaves the order exactly as it found it. There is one
    path out of this function that changes an order's status, and it is the
    last one.
    """
    payment = _locked_payment(order)

    # --- FR-PAY-5: idempotency. A replayed IPN is acknowledged, not applied.
    if payment is not None and payment.status == PaymentStatus.PAID:
        logger.info(
            "sslcommerz IPN replayed for order %s; already paid", order.reference
        )
        return IPNResult(False, REASON_ALREADY_CONFIRMED, order, payment, validation)

    if order.payment_method != PaymentMethod.ONLINE:
        # A Cash on Delivery order is settled by the courier. An IPN naming one
        # is a misconfiguration at best and an attempt to confirm someone
        # else's order at worst.
        logger.warning(
            "sslcommerz IPN for order %s, which is not an online order",
            order.reference,
        )
        return IPNResult(False, REASON_NOT_AN_ONLINE_ORDER, order, payment, validation)

    if order.status != OrderStatus.PENDING:
        reason = (
            REASON_ALREADY_CONFIRMED
            if order.status == OrderStatus.CONFIRMED
            else REASON_ORDER_NOT_PAYABLE
        )
        logger.info(
            "sslcommerz IPN for order %s ignored: order is %s",
            order.reference,
            order.status,
        )
        return IPNResult(False, reason, order, payment, validation)

    # Only now is a row worth opening: this notification is about an online
    # order that is still waiting to be paid for.
    if payment is None:
        payment = _open_payment(order)

    # --- FR-PAY-4, first gate: does the gateway itself say this is real?
    status = str(validation.get("status") or "").upper()
    if status not in sslcommerz.VALIDATION_SUCCESS_STATUSES:
        logger.warning(
            "sslcommerz validation for order %s returned status=%s; not confirming",
            order.reference,
            status or "(none)",
        )
        payment = _reject(
            payment,
            notification=notification,
            validation=validation,
        )
        return IPNResult(False, REASON_VALIDATION_FAILED, order, payment, validation)

    # --- Second gate: the right money, in the right currency.
    currency = str(validation.get("currency") or "").upper()
    if currency != CURRENCY:
        logger.error(
            "sslcommerz validated order %s in %s, not %s; not confirming",
            order.reference,
            currency or "(none)",
            CURRENCY,
        )
        payment = _reject(
            payment,
            notification=notification,
            validation=validation,
        )
        return IPNResult(False, REASON_CURRENCY_MISMATCH, order, payment, validation)

    # `amount` is the transaction amount. `store_amount` is what the store
    # nets after the gateway's fee, and comparing *that* to the order total
    # would reject every genuine payment -- it is deliberately not read here.
    paid = _money(validation.get("amount"))
    expected = Decimal(order.grand_total)
    if paid is None or paid != expected:
        # This is the free-merchandise attack, and it is why the amount is
        # re-checked against the stored total rather than taken on trust.
        logger.error(
            "sslcommerz validated %s for order %s, which totals %s; not confirming",
            paid,
            order.reference,
            expected,
        )
        payment = _reject(
            payment,
            notification=notification,
            validation=validation,
        )
        return IPNResult(False, REASON_AMOUNT_MISMATCH, order, payment, validation)

    # --- Everything checks out. Record the money, then confirm the order.
    payment.status = PaymentStatus.PAID
    payment.method = GATEWAY
    payment.gateway_txn_id = str(
        validation.get("bank_tran_id") or validation.get("val_id") or val_id
    )[:128]
    payment.amount = paid
    payment.currency = currency
    payment.confirmed_at = timezone.now()
    payment.raw_response = _evidence(notification=notification, validation=validation)
    payment.save(
        update_fields=[
            "status",
            "method",
            "gateway_txn_id",
            "amount",
            "currency",
            "confirmed_at",
            "raw_response",
        ]
    )

    try:
        # A savepoint, so that a confirmation the domain refuses -- the only
        # realistic cause being stock that ran out while the customer was on
        # the gateway's page -- does not roll back the record that the money
        # arrived. Losing that record is far worse than an order stuck pending:
        # refunds are manual in v1 (FR-PAY-8), and a manual refund needs
        # evidence. The order is left pending for a human.
        with transaction.atomic():
            order = placement_services.confirm_order(
                order,
                actor=None,
                actor_role=Actor.SYSTEM,
                note="Payment validated by SSLCommerz ({0})".format(
                    payment.gateway_txn_id
                ),
            )
    except DomainError as exc:
        logger.error(
            "order %s was paid (%s %s) but could not be confirmed: %s (%s). "
            "The payment is recorded; the order needs manual attention.",
            order.reference,
            paid,
            currency,
            exc.message,
            exc.code,
        )
        order.refresh_from_db()
        return IPNResult(False, REASON_CONFIRMATION_FAILED, order, payment, validation)

    logger.info(
        "order %s confirmed by validated SSLCommerz payment %s",
        order.reference,
        payment.gateway_txn_id,
    )
    return IPNResult(True, REASON_CONFIRMED, order, payment, validation)


# ---------------------------------------------------------------------------
# Browser callback (FR-PAY-3) -- display only
# ---------------------------------------------------------------------------
# The wording matters as much as the code here. None of these three sentences
# may claim a payment succeeded, because this endpoint has no way of knowing:
# it is reached by a redirect anybody can type.
CALLBACK_MESSAGES = {
    "success": (
        "Thanks. We are confirming your payment with the bank now -- your order "
        "page will show it as confirmed as soon as that comes back."
    ),
    "fail": (
        "The payment did not go through. Nothing has been charged and your order "
        "is still waiting, so you can try again."
    ),
    "cancel": (
        "You cancelled the payment. Your order is still waiting and your cart is "
        "exactly as you left it."
    ),
}


def callback(result, *, reference="", frontend_base_url=None):
    """
    GET /payments/callback/{result}/ -- what to show the customer coming back
    from SSLCommerz (FR-PAY-3).

    **This function reads no rows and writes none.** Not one. That is not
    laziness, it is the requirement: a redirect URL is user-controllable, so
    anything this endpoint reported about an order would be a statement made on
    an attacker's say-so, and anything it wrote would be free merchandise.

    It does not even look the order up. Reporting "this reference is confirmed"
    to whoever opens the URL would turn a display-only endpoint into an oracle
    over the reference space, and the storefront already has an authenticated
    way to read an order.

    `payment_confirmed` is therefore always None -- explicitly "this endpoint
    does not know", so a client cannot mistake a missing field for a false one.
    """
    result = str(result or "").strip().lower()
    if result not in CALLBACK_MESSAGES:
        raise DomainError("Not found.", code="NOT_FOUND", status_code=404)

    reference = str(reference or "").strip()
    if not REFERENCE_PATTERN.match(reference):
        reference = ""

    base = str(frontend_base_url or settings.FRONTEND_BASE_URL).rstrip("/")
    # The SPA's own return screen, not the confirmation page. That screen reads
    # the order back and renders whatever status the server actually holds, so
    # the customer is told the truth even when the IPN has not landed yet.
    # Sending them straight to /order/{reference} would show a confirmation
    # page on the strength of a redirect, which is the thing FR-PAY-3 forbids.
    redirect_url = "{0}/payments/callback/{1}".format(base, result)
    if reference:
        redirect_url += "?tran_id={0}".format(reference)

    return {
        "result": result,
        "reference": reference,
        "message": CALLBACK_MESSAGES[result],
        "payment_confirmed": None,
        "redirect_url": redirect_url,
    }
