# Generated by Django 5.2.6 on 2026-08-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fulltext_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('cpu', 'Processor'), ('cooler', 'CPU cooler'), ('motherboard', 'Motherboard'), ('ram', 'Memory'), ('gpu', 'Graphics card'), ('ssd', 'SSD'), ('hdd', 'Hard drive'), ('psu', 'Power supply'), ('case', 'Case'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], db_index=True, max_length=16)),
                ('socket', models.CharField(blank=True, help_text='AM5, LGA1700, ... (CPU and motherboard)', max_length=32)),
                ('supported_sockets', models.JSONField(blank=True, default=list)),
                ('ram_type', models.CharField(blank=True, help_text='DDR4, DDR5', max_length=16)),
                ('ram_slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_gb', models.PositiveIntegerField(blank=True, help_text='Total capacity of a memory kit or drive.', null=True)),
                ('module_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(blank=True, help_text='ATX, Micro-ATX, Mini-ITX (motherboard)', max_length=24)),
                ('supported_form_factors', models.JSONField(blank=True, default=list, help_text='What a case accepts.')),
                ('length_mm', models.PositiveIntegerField(blank=True, help_text='Card length (GPU).', null=True)),
                ('max_gpu_length_mm', models.PositiveIntegerField(blank=True, help_text='Longest card a case takes.', null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, help_text='Cooler height.', null=True)),
                ('max_cooler_height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('power_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('tdp_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('cooler_max_tdp_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('wattage', models.PositiveIntegerField(blank=True, null=True)),
                ('efficiency_rating', models.CharField(blank=True, help_text='80+ Bronze, 80+ Gold, ...', max_length=24)),
            ],
            options={
                'db_table': 'catalog_component_profile',
            },
        ),
        migrations.AlterModelOptions(
            name='productspec',
            options={'ordering': ['group_order', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productspec',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productspec',
            name='group_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='catalog_pro_is_feat_b968c0_idx'),
        ),
        migrations.AddField(
            model_name='componentprofile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='componentprofile',
            index=models.Index(fields=['slot', 'socket'], name='catalog_com_slot_27c9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='componentprofile',
            index=models.Index(fields=['slot', 'ram_type'], name='catalog_com_slot_46cc3e_idx'),
        ),
    ]
