# Generated by Django 5.2.6 on 2026-08-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_componentprofile_alter_productspec_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_license_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='attribution',
            field=models.CharField(blank=True, help_text='Author, as the licence requires it to be shown.', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
