# Generated by Django 5.2.6 on 2026-08-19 07:08

import apps.common.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage points for percent coupons, BDT for fixed.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', apps.common.fields.MoneyField(blank=True, help_text='Caps a percentage discount. Ignored for fixed coupons.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_value', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed. Null is unlimited.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('scope_type', models.CharField(choices=[('all', 'Entire catalogue'), ('category', 'Specific categories'), ('product', 'Specific products')], default='all', max_length=16)),
                ('scope_ids', models.JSONField(blank=True, default=list, help_text='Category or product IDs when scoped.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'promotions_coupon',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'valid_until'], name='promotions__is_acti_56989c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', apps.common.fields.MoneyField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promotions_coupon_redemption',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='promotions__coupon__f914a7_idx')],
            },
        ),
    ]
