# Generated by Django 5.2.6 on 2026-08-23 07:17

import apps.builds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_componentprofile_alter_productspec_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My build', max_length=120)),
                ('share_token', models.CharField(default=apps.builds.models.generate_share_token, editable=False, max_length=32, unique=True)),
                ('is_compatible', models.BooleanField(default=True)),
                ('estimated_watts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'builds_pc_build',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PCBuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('cpu', 'Processor'), ('cooler', 'CPU cooler'), ('motherboard', 'Motherboard'), ('ram', 'Memory'), ('gpu', 'Graphics card'), ('ssd', 'SSD'), ('hdd', 'Hard drive'), ('psu', 'Power supply'), ('case', 'Case'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse')], max_length=16)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='builds.pcbuild')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'builds_pc_build_item',
                'ordering': ['slot'],
            },
        ),
        migrations.AddIndex(
            model_name='pcbuild',
            index=models.Index(fields=['user', '-updated_at'], name='builds_pc_b_user_id_91bf8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcbuilditem',
            constraint=models.UniqueConstraint(fields=('build', 'slot'), name='one_part_per_slot'),
        ),
    ]
