# Generated by Django 5.2.6 on 2026-08-19 07:08

import apps.common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('flat_rate', apps.common.fields.MoneyField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_kg_rate', apps.common.fields.MoneyField(default=0, help_text='Charged on weight above base_weight_grams.', validators=[django.core.validators.MinValueValidator(0)])),
                ('base_weight_grams', models.PositiveIntegerField(default=1000, help_text='Weight included in the flat rate.')),
                ('free_shipping_threshold', apps.common.fields.MoneyField(blank=True, help_text='Order subtotal at or above which shipping is free. Null disables it.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cod_allowed', models.BooleanField(default=True)),
                ('districts', models.JSONField(default=list, help_text='District names that map an address to this zone.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_zone',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
