# Generated by Django 5.2.6 on 2026-08-19 07:08

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16)),
                ('gateway_txn_id', models.CharField(blank=True, db_index=True, help_text='SSLCommerz val_id / bank_tran_id once validated.', max_length=128)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Gateway session token returned by the initiate call.', max_length=128)),
                ('amount', apps.common.fields.MoneyField()),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=16)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Retained for gateway reconciliation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx')],
            },
        ),
    ]
